'use client';

import { useCallback, useEffect, useState } from 'react';
import { AppShell, Card, EmptyState, Notice, PageHeader, Skeleton, StatusBadge, formatDate, localePath, type Locale } from '@tamkeen/ui';
import './workspace.css';
import { DownloadButton } from './download-button';

class UnauthenticatedError extends Error {}
const api = async (path: string, method: 'GET' | 'POST' = 'GET', body?: unknown) => {
  const response = await fetch(`/api/v1${path}`, { method, credentials: 'include', headers: body ? { 'content-type': 'application/json' } : {}, ...(body ? { body: JSON.stringify(body) } : {}) });
  const payload = await response.json().catch(() => ({}));
  if (response.status === 401) throw new UnauthenticatedError();
  if (!response.ok) throw new Error(payload?.error?.code === 'conflict' ? 'تغيّرت الحالة. أعد التحميل واقرأ ما تغيّر.' : 'تعذر إكمال العملية.');
  return payload.data;
};

function Shell({ locale, path, signedIn, children }: { locale: Locale; path: string; signedIn: boolean; children: React.ReactNode }) {
  return <AppShell locale={locale} path={path} signedIn={signedIn} userActions={<a className="tmk-button tmk-button--quiet" href={localePath(locale, '/app')}>مساحتي</a>}>{children}</AppShell>;
}

type Notification = { id: string; title: string; body: string; safePath: string; readAt: string | null; createdAt: string };
type NotificationPreferences = { emailReminders: boolean; emailFollowUpdates: boolean; version: number };
export function MyNotifications({ locale }: { locale: Locale }) {
  const [items, setItems] = useState<Notification[] | null>(null); const [preferences, setPreferences] = useState<NotificationPreferences | null>(null); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [signedIn, setSignedIn] = useState(true);
  const load = useCallback(async () => { const [notifications, saved] = await Promise.all([api('/me/notifications'), api('/me/notification-preferences')]); setItems(notifications as Notification[]); setPreferences(saved as NotificationPreferences); }, []);
  useEffect(() => { void load().catch(e => e instanceof UnauthenticatedError ? setSignedIn(false) : setError('تعذر تحميل الإشعارات.')); }, [load]);
  const act = async (run: () => Promise<unknown>) => { try { await run(); await load(); } catch { setError('تعذر حفظ حالة القراءة.'); } };
  const savePreferences = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!preferences) return; const form = new FormData(event.currentTarget); setError(''); setNotice(''); try { const saved = await api('/me/notification-preferences', 'POST', { emailReminders: form.get('emailReminders') === 'on', emailFollowUpdates: form.get('emailFollowUpdates') === 'on', version: preferences.version }) as NotificationPreferences; setPreferences(saved); setNotice('حُفظت تفضيلات البريد الاختيارية. تبقى إشعارات التشغيل داخل المنصة مفعّلة.'); } catch { setError('تعذر حفظ التفضيلات؛ أعد تحميل الصفحة.'); } };
  return <Shell locale={locale} path="/app/notifications" signedIn={signedIn}>
    <PageHeader eyebrow="حسابي" title="الإشعارات" lead="رسائل تشغيل خاصة بروابط داخلية آمنة. فشل البريد لا يعكس نجاح العملية التي أنشأت الإشعار." actions={items?.some(item => !item.readAt) ? <button className="tmk-button tmk-button--secondary" onClick={() => void act(() => api('/me/notifications/read-all', 'POST', { through: new Date().toISOString() }))}>علّم الكل مقروءًا</button> : undefined} />
    {error ? <Notice tone="danger">{error}</Notice> : null}
    {notice ? <Notice tone="success">{notice}</Notice> : null}
    {signedIn && preferences ? <Card title="تفضيلات التسليم"><form onSubmit={savePreferences}><label className="tmk-field"><span><input type="checkbox" name="emailReminders" defaultChecked={preferences.emailReminders} key={`reminders-${preferences.version}`} /> تذكيرات المواعيد عبر البريد</span></label><label className="tmk-field"><span><input type="checkbox" name="emailFollowUpdates" defaultChecked={preferences.emailFollowUpdates} key={`follows-${preferences.version}`} /> تحديثات الجهات والمشاريع المتابَعة عبر البريد</span></label><p className="tmk-field__hint">الإشعارات التشغيلية داخل المنصة إلزامية ولا يمكن تعطيلها هنا. لا يوجد SMS في هذه النسخة.</p><button className="tmk-button tmk-button--secondary">حفظ التفضيلات</button></form></Card> : null}
    {!signedIn ? <Notice tone="warning">سجّل الدخول لترى إشعاراتك.</Notice> : items === null ? <Skeleton lines={5} label="جارٍ التحميل" /> : items.length === 0 ? <EmptyState title="لا إشعارات">تظهر هنا الأحداث التي تحتاج انتباهك، لا الرسائل التسويقية.</EmptyState> : <Card title="الأحدث أولًا"><div className="tmk-stack">{items.map(item => <article className="tmk-row" key={item.id}><div><strong>{item.title}</strong><p>{item.body}</p><span className="tmk-field__hint">{formatDate(item.createdAt, locale)}</span></div><div className="tmk-row__actions"><StatusBadge tone={item.readAt ? 'neutral' : 'info'}>{item.readAt ? 'مقروء' : 'جديد'}</StatusBadge>{item.safePath ? <a className="tmk-button tmk-button--quiet" href={localePath(locale, item.safePath)} onClick={() => { if (!item.readAt) void act(() => api(`/notifications/${item.id}/read`, 'POST')); }}>افتح</a> : null}</div></article>)}</div></Card>}
  </Shell>;
}

type Ticket = { id: string; reference: string; title: string; category: string; state: string; priority: string; version: number; updatedAt: string; replies?: Array<{ id: string; body: string; authorKind: string; createdAt: string }> };
export function SupportTickets({ locale, ticketId, create = false }: { locale: Locale; ticketId?: string; create?: boolean }) {
  const path = create ? '/contact' : ticketId ? `/app/tickets/${ticketId}` : '/app/tickets';
  const [tickets, setTickets] = useState<Ticket[] | null>(null); const [detail, setDetail] = useState<Ticket | null>(null); const [signedIn, setSignedIn] = useState(true); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = useCallback(async () => { if (ticketId) setDetail(await api(`/tickets/${ticketId}`) as Ticket); else setTickets(await api('/me/tickets') as Ticket[]); }, [ticketId]);
  useEffect(() => { void load().catch(e => e instanceof UnauthenticatedError ? setSignedIn(false) : setError('تعذر تحميل التذاكر.')); }, [load]);
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); setError(''); try { const created = await api('/tickets', 'POST', { subjectType: String(form.get('subjectType')), category: String(form.get('category')), title: String(form.get('title')), body: String(form.get('body')) }) as Ticket; setNotice(`أُرسلت التذكرة ${created.reference}. سجل خاص لا يغير حقًا ماليًا.`); event.currentTarget.reset(); await load(); } catch { setError('تحقق من الحقول وسجّل الدخول ثم أعد المحاولة.'); } };
  const reply = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await api(`/tickets/${ticketId}/replies`, 'POST', { body: String(form.get('body')) }); event.currentTarget.reset(); await load(); } catch { setError('تعذر إرسال الرد.'); } };
  return <Shell locale={locale} path={path} signedIn={signedIn}><PageHeader eyebrow="الدعم" title={create ? 'تواصل مع الدعم' : ticketId ? detail?.reference ?? 'التذكرة' : 'تذاكر الدعم'} lead="السجل خاص بينك وبين الفريق المخول. الشكوى المالية لا تمحو قيدًا ولا تغيّر حقًا تلقائيًا." />{error ? <Notice tone="danger">{error}</Notice> : null}{notice ? <Notice tone="success">{notice}</Notice> : null}
    {create ? <Card title="تذكرة جديدة"><form onSubmit={submit}><div className="tmk-field"><label htmlFor="subjectType">المورد</label><select id="subjectType" name="subjectType" className="tmk-field__control"><option value="general">عام</option><option value="project">مشروع</option><option value="payment">دفع</option><option value="identity">هوية</option></select></div><div className="tmk-field"><label htmlFor="category">النوع</label><select id="category" name="category" className="tmk-field__control"><option value="support">مساعدة</option><option value="content">بلاغ محتوى</option><option value="access">وصول وخصوصية</option></select></div><div className="tmk-field"><label htmlFor="ticketTitle">العنوان</label><input id="ticketTitle" name="title" required minLength={5} maxLength={200} className="tmk-field__control" /></div><div className="tmk-field"><label htmlFor="ticketBody">التفاصيل</label><textarea id="ticketBody" name="body" required minLength={10} maxLength={2000} rows={5} className="tmk-field__control" /></div><button className="tmk-button tmk-button--primary">أرسل التذكرة</button></form></Card> : ticketId ? detail ? <><Card title="الحالة"><StatusBadge tone={detail.state === 'resolved' ? 'success' : 'info'}>{detail.state}</StatusBadge><p>{detail.title}</p></Card><Card title="المراسلات"><div className="tmk-stack">{detail.replies?.map(replyItem => <article className="tmk-row" key={replyItem.id}><div><strong>{replyItem.authorKind === 'staff' ? 'فريق الدعم' : 'أنت'}</strong><p>{replyItem.body}</p><span className="tmk-field__hint">{formatDate(replyItem.createdAt, locale)}</span></div></article>)}</div>{detail.state !== 'closed' ? <form onSubmit={reply}><div className="tmk-field"><label htmlFor="replyBody">ردك</label><textarea id="replyBody" name="body" required minLength={2} maxLength={4000} rows={4} className="tmk-field__control" /></div><button className="tmk-button tmk-button--primary">أرسل الرد</button></form> : null}</Card></> : <Skeleton lines={5} label="جارٍ التحميل" /> : tickets === null ? <Skeleton lines={5} label="جارٍ التحميل" /> : tickets.length === 0 ? <EmptyState title="لا تذاكر" action={<a className="tmk-button tmk-button--primary" href={localePath(locale, '/contact')}>تذكرة جديدة</a>}>إذا احتجت مساعدة افتح تذكرة تصف المورد والمشكلة.</EmptyState> : <Card title="تذاكري"><div className="tmk-stack">{tickets.map(ticket => <a key={ticket.id} className="tmk-row" href={localePath(locale, `/app/tickets/${ticket.id}`)}><strong>{ticket.reference} — {ticket.title}</strong><span className="tmk-field__hint">{ticket.state} · {formatDate(ticket.updatedAt, locale)}</span></a>)}</div></Card>}
  </Shell>;
}

export function AdminOperations({ locale, mode, ticketId }: { locale: Locale; mode: 'tickets' | 'audit'; ticketId?: string }) {
  const [rows, setRows] = useState<Array<Record<string, unknown>> | null>(null); const [ticket, setTicket] = useState<Ticket | null>(null); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = useCallback(async () => {
    if (ticketId) setTicket(await api(`/tickets/${ticketId}`) as Ticket);
    else setRows(await api(mode === 'tickets' ? '/admin/tickets' : '/admin/audit') as Array<Record<string, unknown>>);
  }, [mode, ticketId]);
  useEffect(() => { void load().catch(() => setError('لا تملك المنحة المطلوبة أو تعذر التحميل.')); }, [load]);
  const mutate = async (path: string, body: unknown, message: string) => { setError(''); try { await api(path, 'POST', body); setNotice(message); await load(); } catch { setError('تغيّرت الحالة أو لا تملك المنحة المطلوبة. أعد التحميل.'); } };
  const submitReply = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); await mutate(`/tickets/${ticketId}/replies`, { body: String(form.get('body')) }, 'أُضيف الرد إلى السجل غير القابل للمحو.'); event.currentTarget.reset(); };
  const submitResolve = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!ticket) return; const form = new FormData(event.currentTarget); await mutate(`/admin/tickets/${ticket.id}/resolve`, { resolutionCode: String(form.get('resolutionCode')), resolution: String(form.get('resolution')), version: ticket.version }, 'سُجل الحل. لم يتغير أي حق مالي تلقائيًا.'); };
  const requestAuditExport = async () => { try { const job = await api('/admin/audit-exports', 'POST', { reason: 'Independent review export requested from the scoped audit screen.' }) as { id: string }; window.location.href = localePath(locale, `/app/exports/${job.id}`); } catch { setError('تعذر إنشاء ملف التدقيق أو لا تملك منحة التصدير.'); } };
  const path = ticketId ? `/admin/tickets/${ticketId}` : mode === 'tickets' ? '/admin/tickets' : '/admin/audit';
  return <Shell locale={locale} path={path} signedIn><PageHeader eyebrow={mode === 'tickets' ? 'ADM-07' : 'ADM-08'} title={ticketId ? ticket?.reference ?? 'التذكرة' : mode === 'tickets' ? 'تذاكر الدعم والبلاغات' : 'سجل التدقيق'} lead={mode === 'tickets' ? 'قائمة خاصة حسب المنحة والأولوية. التجميد محدد النطاق ولا يعيد النشر تلقائيًا.' : 'قراءة منقحة وغير قابلة للتعديل. لا رموز جلسات ولا payloads دفع.'} actions={mode === 'audit' ? <button className="tmk-button tmk-button--secondary" onClick={() => void requestAuditExport()}>صدّر CSV منقحًا</button> : undefined} />
    {error ? <Notice tone="danger">{error}</Notice> : null}{notice ? <Notice tone="success">{notice}</Notice> : null}
    {ticketId ? ticket === null ? <Skeleton lines={7} label="جارٍ التحميل" /> : <><Card title="إدارة الحالة"><p>{ticket.title}</p><StatusBadge tone={ticket.state === 'resolved' ? 'success' : 'info'}>{ticket.state}</StatusBadge><div className="tmk-row__actions"><button className="tmk-button tmk-button--secondary" onClick={() => void mutate(`/admin/tickets/${ticket.id}/claim`, { version: ticket.version }, 'أُسندت التذكرة إليك.')}>استلم التذكرة</button><button className="tmk-button tmk-button--quiet" onClick={() => void mutate(`/admin/tickets/${ticket.id}/escalate`, { priority: 'high', nextActionAt: new Date(Date.now() + 86_400_000).toISOString(), version: ticket.version }, 'رُفعت الأولوية وسُجل موعد الإجراء التالي.')}>صعّد</button></div></Card><Card title="المراسلات"><div className="tmk-stack">{ticket.replies?.map(item => <article className="tmk-row" key={item.id}><div><strong>{item.authorKind === 'staff' ? 'فريق الدعم' : 'صاحب التذكرة'}</strong><p>{item.body}</p><span className="tmk-field__hint">{formatDate(item.createdAt, locale)}</span></div></article>)}</div><form onSubmit={submitReply}><div className="tmk-field"><label htmlFor="adminReply">رد الدعم</label><textarea id="adminReply" name="body" required minLength={2} maxLength={4000} rows={4} className="tmk-field__control" /></div><button className="tmk-button tmk-button--primary">أضف الرد</button></form></Card><Card title="الحل"><form onSubmit={submitResolve}><div className="tmk-field"><label htmlFor="resolutionCode">رمز الحل</label><input id="resolutionCode" name="resolutionCode" required minLength={2} maxLength={50} className="tmk-field__control" /></div><div className="tmk-field"><label htmlFor="resolution">شرح الحل والحقوق الباقية</label><textarea id="resolution" name="resolution" required minLength={10} maxLength={2000} rows={4} className="tmk-field__control" /></div><button className="tmk-button tmk-button--primary">حل التذكرة</button></form></Card></> : rows === null ? <Skeleton lines={7} label="جارٍ التحميل" /> : rows.length === 0 ? <EmptyState title="القائمة فارغة">لا عناصر ضمن نطاقك الحالي.</EmptyState> : <Card title="النتائج"><div className="tmk-stack">{rows.map((row, index) => mode === 'tickets' ? <a className="tmk-row" href={localePath(locale, `/admin/tickets/${String(row.id)}`)} key={String(row.id ?? index)}><div><strong>{String(row.reference ?? 'تذكرة')}</strong><p>{String(row.title ?? '')}</p></div><span className="tmk-field__hint">{String(row.state ?? '')}</span></a> : <article className="tmk-row" key={String(row.id ?? index)}><div><strong>{String(row.action ?? 'حدث')}</strong><p>{String(row.resourceId ?? '')}</p></div><span className="tmk-field__hint">منقح</span></article>)}</div></Card>}
  </Shell>;
}

type ExportJob = { id: string; kind: string; state: string; filename: string; expiresAt: string | null; lastErrorCode: string; version: number; createdAt: string };
export function ExportTracker({ locale, jobId }: { locale: Locale; jobId: string }) {
  const [job, setJob] = useState<ExportJob | null>(null); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = useCallback(async () => setJob(await api(`/exports/${jobId}`) as ExportJob), [jobId]);
  useEffect(() => { void load().catch(() => setError('الملف غير موجود أو لم تعد تملك صلاحية الوصول إليه.')); }, [load]);
  const act = async (path: string, body?: unknown) => { setError(''); try { const next = await api(path, 'POST', body) as ExportJob; setJob(next); setNotice('حُفظ التغيير.'); } catch { setError('تعذر تنفيذ العملية في الحالة الحالية.'); } };
  return <Shell locale={locale} path={`/app/exports/${jobId}`} signedIn><PageHeader eyebrow="التصدير" title="ملف التصدير" lead="يُعاد فحص الملكية والصلاحية عند كل قراءة وتنزيل. انتهاء النسخة لا يحذف السجلات المصدر." />{error ? <Notice tone="danger">{error}</Notice> : null}{notice ? <Notice tone="success">{notice}</Notice> : null}{job === null ? <Skeleton lines={5} label="جارٍ التحميل" /> : <Card title={job.filename || job.kind}><StatusBadge tone={job.state === 'ready' ? 'success' : job.state === 'failed' ? 'danger' : 'info'}>{job.state}</StatusBadge><p className="tmk-field__hint">أُنشئ {formatDate(job.createdAt, locale, true)}{job.expiresAt ? ` · ينتهي ${formatDate(job.expiresAt, locale, true)}` : ''}</p><div className="tmk-row__actions">{job.state === 'ready' ? <DownloadButton endpoint={`/exports/${job.id}/download`} label="نزّل الملف" /> : null}{['failed', 'expired'].includes(job.state) ? <button className="tmk-button tmk-button--secondary" onClick={() => void act(`/exports/${job.id}/regenerate`)}>أعد الإنشاء</button> : null}{['ready', 'failed', 'expired'].includes(job.state) ? <button className="tmk-button tmk-button--quiet" onClick={() => void act(`/exports/${job.id}/revoke`, { version: job.version })}>ألغِ النسخة</button> : null}<button className="tmk-button tmk-button--quiet" onClick={() => void load()}>حدّث الحالة</button></div></Card>}</Shell>;
}

type OperationsOverview = { asOf: string; notificationsPending: number; notificationsDead: number; exportsPending: number; exportsFailed: number; incidentsOpen: number; workerLastSeen: string | null };
export function OperationsDashboard({ locale }: { locale: Locale }) {
  const [data, setData] = useState<OperationsOverview | null>(null); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = useCallback(async () => setData(await api('/admin/operations') as OperationsOverview), []);
  useEffect(() => { void load().catch(() => setError('لا تملك منحة التشغيل أو تعذر تحميل الحالة.')); }, [load]);
  const restore = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await api('/admin/restore-drills', 'POST', { environment: String(form.get('environment')), evidenceRef: String(form.get('evidenceRef')), measuredRpoMins: Number(form.get('rpo')), measuredRtoMins: Number(form.get('rto')), outcome: String(form.get('outcome')), notes: String(form.get('notes')), performedAt: new Date().toISOString() }); setNotice('سُجل التمرين بقياساته ودليله.'); event.currentTarget.reset(); } catch { setError('تعذر تسجيل التمرين.'); } };
  return <Shell locale={locale} path="/admin/operations" signedIn><PageHeader eyebrow="إدارة المنصة" title="مراقبة التشغيل" lead="الأعمار والفشل والحوادث دون payloads أو أسرار. إعادة المحاولة هنا لعمل غير مالي فقط؛ النتيجة المالية المجهولة تُحسم بالاستعلام." actions={<button className="tmk-button tmk-button--quiet" onClick={() => void load()}>حدّث</button>} />{error ? <Notice tone="danger">{error}</Notice> : null}{notice ? <Notice tone="success">{notice}</Notice> : null}{data === null ? <Skeleton lines={6} label="جارٍ التحميل" /> : <Card title="الحالة الحالية"><div className="tmk-grid tmk-grid--stats"><div><strong>{data.notificationsPending}</strong><p>إشعارات تنتظر/تعاد</p></div><div><strong>{data.notificationsDead}</strong><p>dead-letter</p></div><div><strong>{data.exportsPending}</strong><p>تصديرات قيد العمل</p></div><div><strong>{data.exportsFailed}</strong><p>تصديرات فاشلة</p></div><div><strong>{data.incidentsOpen}</strong><p>حوادث مفتوحة</p></div></div><p className="tmk-field__hint">آخر نبضة worker: {data.workerLastSeen ? formatDate(data.workerLastSeen, locale, true) : 'غير متاحة'}</p></Card>}<Card title="سجل تمرين استعادة فعلي"><form onSubmit={restore}><div className="tmk-field"><label htmlFor="environment">البيئة</label><input id="environment" name="environment" required minLength={2} className="tmk-field__control" /></div><div className="tmk-field"><label htmlFor="evidenceRef">مرجع الدليل</label><input id="evidenceRef" name="evidenceRef" required minLength={3} className="tmk-field__control" /></div><div className="tmk-grid tmk-grid--2"><div className="tmk-field"><label htmlFor="rpo">RPO بالدقائق</label><input id="rpo" name="rpo" type="number" min="0" required className="tmk-field__control" /></div><div className="tmk-field"><label htmlFor="rto">RTO بالدقائق</label><input id="rto" name="rto" type="number" min="0" required className="tmk-field__control" /></div></div><div className="tmk-field"><label htmlFor="outcome">النتيجة</label><select id="outcome" name="outcome" className="tmk-field__control"><option value="passed">ناجح</option><option value="partial">جزئي</option><option value="failed">فاشل</option></select></div><div className="tmk-field"><label htmlFor="notes">ملاحظات</label><textarea id="notes" name="notes" maxLength={2000} className="tmk-field__control" /></div><button className="tmk-button tmk-button--primary">سجل التمرين</button></form></Card></Shell>;
}
