'use client';

import { useCallback, useEffect, useState, type FormEvent, type ReactNode } from 'react';
import {
  AppShell, Card, DataTable, EmptyState, ErrorState, Ltr, Notice, PageHeader,
  Skeleton, Stat, StatusBadge, formatDate, localePath, translator, type Locale
} from '@tamkeen/ui';
import './workspace.css';

/**
 * PART-10 screens: PER-10 the skills profile, PER-11/12 applying and following an application,
 * PER-13 a trainee's own training, PRG-01..05 the operator's side, and the independent review.
 *
 * What these screens must get right, because getting it wrong misleads somebody about their future:
 *
 *  - **Training is not employment.** No screen implies a job, and the ones a candidate reads say so
 *    in words at the moment they would otherwise assume it.
 *  - **A seat is invited, then accepted, then held.** Three different things, never one badge.
 *  - **Nothing about a person leaves their account without their say-so**, and the preview showing
 *    what an operator receives is generated by the server from the same allowlist the operator reads.
 *  - **An attendance record can decide whether somebody is paid**, so a change is a revision with a
 *    reason, and a dispute goes to somebody who did not make the record.
 */

class UnauthenticatedError extends Error {}

const api = async (path: string, method: 'GET' | 'POST' | 'PATCH' | 'PUT' = 'GET', body?: unknown) => {
  const response = await fetch(`/api/v1${path}`, {
    method, credentials: 'include',
    headers: body ? { 'content-type': 'application/json' } : {},
    ...(body ? { body: JSON.stringify(body) } : {})
  });
  const payload = await response.json().catch(() => ({}));
  if (response.status === 401) throw new UnauthenticatedError('unauthenticated');
  if (!response.ok) throw new Error(message(payload?.error?.code, response.status));
  return payload.data;
};

function message(code: string | undefined, status: number): string {
  const messages: Record<string, string> = {
    forbidden: 'لا تملك صلاحية هذا الإجراء ضمن هذه الدفعة أو هذا البرنامج.',
    not_found: 'المورد غير موجود ضمن نطاقك.',
    conflict: 'تغيّرت الحالة: قد يكون الموعد النهائي مضى، أو امتلأت المقاعد، أو انتهت مهلة قبول المقعد، أو النسخة التي بين يديك قديمة. أعد التحميل واقرأ ما تغيّر.',
    // Written for the person reading these screens — a candidate — not for an operator. The
    // operator's screens carry their own wording for the same code.
    invalid_input: 'تحقق من الحقول: اكتب دافعك للتقديم، ووافق على مشاركة ملفك، واملأ ملف المهارات قبل الإرسال.'
  };
  return messages[code ?? ''] ?? `تعذر إكمال العملية (${status}).`;
}

type Tone = 'neutral' | 'success' | 'warning' | 'danger' | 'info';


const applicationStates: Record<string, { text: string; tone: Tone }> = {
  draft: { text: 'مسودة', tone: 'neutral' },
  submitted: { text: 'أُرسل', tone: 'info' },
  screening: { text: 'قيد الفرز', tone: 'info' },
  shortlisted: { text: 'ضمن القائمة القصيرة', tone: 'info' },
  interview: { text: 'مقابلة', tone: 'warning' },
  accepted: { text: 'مقبول — بانتظار قبولك للمقعد', tone: 'success' },
  waitlisted: { text: 'قائمة انتظار', tone: 'warning' },
  rejected: { text: 'غير مقبول', tone: 'danger' },
  withdrawn: { text: 'مسحوب', tone: 'neutral' },
  discarded: { text: 'مسودة ملغاة', tone: 'neutral' }
};

const enrollmentStates: Record<string, { text: string; tone: Tone }> = {
  invited: { text: 'مقعد مدعو — لم يُقبل بعد', tone: 'warning' },
  confirmed: { text: 'مقعد مؤكَّد', tone: 'success' },
  active: { text: 'متدرب نشط', tone: 'success' },
  completed: { text: 'أكمل', tone: 'success' },
  dropped_out: { text: 'انسحب', tone: 'neutral' },
  terminated: { text: 'أُنهي التحاقه', tone: 'danger' },
  expired: { text: 'انتهت مهلة المقعد', tone: 'neutral' }
};

const interviewStates: Record<string, { text: string; tone: Tone }> = {
  proposed: { text: 'موعد مقترح — بانتظار تأكيدك', tone: 'warning' },
  confirmed: { text: 'مؤكَّد', tone: 'success' },
  reschedule_requested: { text: 'طلبتَ تغيير الموعد — الموعد الأصلي قائم', tone: 'info' },
  completed: { text: 'تمت', tone: 'neutral' },
  cancelled: { text: 'ملغاة', tone: 'neutral' }
};

const attendanceLabels: Record<string, { text: string; tone: Tone }> = {
  present: { text: 'حاضر', tone: 'success' },
  late: { text: 'متأخر', tone: 'warning' },
  excused: { text: 'غياب بعذر', tone: 'info' },
  absent: { text: 'غائب', tone: 'danger' }
};

/** Repeated wherever somebody might otherwise read a seat as a job. */
function NotEmployment({ children }: { children?: ReactNode }) {
  return (
    <Notice tone="warning" title="التدريب ليس توظيفًا">
      <p style={{ marginBlockEnd: 0 }}>
        {children ?? 'قبولك في التدريب ليس قبولًا لوظيفة، وإكمال البرنامج لا يمنحك حقًا في وظيفة. ما يعلنه البرنامج عن الوظائف مكتوب في صفحته العامة بصيغته الدقيقة.'}
      </p>
    </Notice>
  );
}

// ---------------------------------------------------------------------------------------------
// PER-10 — the skills profile
// ---------------------------------------------------------------------------------------------

interface CandidateProfile {
  exists: boolean; headline: string; summary: string; city: string; availability: string;
  education: string; experience: string; skills: string[]; cvReference: string;
  cvUploadAvailable: boolean; shareWithOperators: boolean; shareContact: boolean; version: number;
}

export function CareerProfile({ locale }: { locale: Locale }) {
  const L = (path: string) => localePath(locale, path);
  const t = translator(locale);
  const [profile, setProfile] = useState<CandidateProfile | null>(null);
  const [preview, setPreview] = useState<{ shared: boolean; withheld: string[]; profile: Record<string, unknown> } | null>(null);
  const [signedIn, setSignedIn] = useState(true);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');

  const load = useCallback(async () => setProfile(await api('/me/candidate-profile') as CandidateProfile), []);

  useEffect(() => {
    let active = true;
    (async () => {
      try { await load(); }
      catch (e) {
        if (!active) return;
        if (e instanceof UnauthenticatedError) setSignedIn(false);
        else setError(e instanceof Error ? e.message : 'تعذر تحميل الملف.');
      }
      finally { if (active) setLoading(false); }
    })();
    return () => { active = false; };
  }, [load]);

  const save = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (busy || !profile) return;
    const form = new FormData(event.currentTarget);
    setBusy(true); setError(''); setNotice('');
    try {
      const skills = String(form.get('skills') ?? '').split(/[,،]/).map(skill => skill.trim()).filter(Boolean);
      await api('/me/candidate-profile', 'PATCH', {
        headline: String(form.get('headline') ?? ''),
        summary: String(form.get('summary') ?? ''),
        city: String(form.get('city') ?? ''),
        availability: String(form.get('availability') ?? ''),
        education: String(form.get('education') ?? ''),
        experience: String(form.get('experience') ?? ''),
        cvReference: String(form.get('cvReference') ?? ''),
        skills,
        shareWithOperators: form.get('shareWithOperators') === 'on',
        shareContact: form.get('shareContact') === 'on',
        ...(profile.exists ? { version: profile.version } : {})
      });
      await load();
      setPreview(null);
      setNotice('حُفظ الملف. تسري الموافقة على المشاركة فورًا، وسحبها يخفيه عن كل جهة مشغّلة في الحال.');
    } catch (e) {
      setError(e instanceof Error ? e.message : 'تعذر حفظ الملف.');
    } finally { setBusy(false); }
  };

  const shell = (children: ReactNode) => (
    <AppShell locale={locale} path="/app/career/profile" signedIn={signedIn}
      userActions={<a className="tmk-button tmk-button--quiet" href={L('/app')}>{t('personalWorkspace')}</a>}>
      {error ? <Notice tone="danger" live="assertive">{error}</Notice> : null}
      {notice ? <Notice tone="success" live="polite">{notice}</Notice> : null}
      {children}
    </AppShell>
  );

  if (loading) return shell(<Skeleton lines={6} label={t('loading')} />);
  if (!signedIn) {
    return shell(
      <ErrorState title={t('forbiddenTitle')} onRetry={<a className="tmk-button tmk-button--primary" href={`${L('/login')}?returnTo=${encodeURIComponent(L('/app/career/profile'))}`}>{t('signIn')}</a>}>
        {t('forbiddenBody')}
      </ErrorState>
    );
  }
  if (!profile) return shell(<ErrorState title="تعذر التحميل">أعد المحاولة.</ErrorState>);

  return shell(
    <>
      <PageHeader
        dashboard
        title="ملف المهارات"
        lead="هذا ما قد تختار مشاركته مع جهة مشغّلة عند التقديم. لا يغادر حسابك شيء منه قبل أن توافق، والموافقة قابلة للسحب في أي وقت."
      />

      <Card title="الملف">
        <form onSubmit={event => void save(event)}>
          <div className="tmk-field">
            <label className="tmk-field__label" htmlFor="headline">سطر التعريف</label>
            <input id="headline" name="headline" className="tmk-field__control" defaultValue={profile.headline} maxLength={200} />
          </div>
          <div className="tmk-field">
            <label className="tmk-field__label" htmlFor="summary">نبذة</label>
            <textarea id="summary" name="summary" className="tmk-field__control" rows={4} defaultValue={profile.summary} maxLength={2000} />
          </div>
          <div className="tmk-grid tmk-grid--stats">
            <div className="tmk-field">
              <label className="tmk-field__label" htmlFor="city">المدينة</label>
              <input id="city" name="city" className="tmk-field__control" defaultValue={profile.city} maxLength={100} />
            </div>
            <div className="tmk-field">
              <label className="tmk-field__label" htmlFor="availability">التوفر</label>
              <span className="tmk-field__hint" id="availability-hint">مثل: مساءً، أو ابتداءً من أيار.</span>
              <input id="availability" name="availability" className="tmk-field__control" defaultValue={profile.availability} maxLength={200} aria-describedby="availability-hint" />
            </div>
          </div>
          <div className="tmk-field">
            <label className="tmk-field__label" htmlFor="skills">المهارات</label>
            <span className="tmk-field__hint" id="skills-hint">افصل بينها بفاصلة. هذه ما تُفلتر عليه البرامج.</span>
            <input id="skills" name="skills" className="tmk-field__control" defaultValue={profile.skills.join('، ')} aria-describedby="skills-hint" />
          </div>
          <div className="tmk-field">
            <label className="tmk-field__label" htmlFor="education">التعليم</label>
            <textarea id="education" name="education" className="tmk-field__control" rows={3} defaultValue={profile.education} maxLength={1000} />
          </div>
          <div className="tmk-field">
            <label className="tmk-field__label" htmlFor="experience">الخبرة</label>
            <textarea id="experience" name="experience" className="tmk-field__control" rows={4} defaultValue={profile.experience} maxLength={2000} />
          </div>
          <div className="tmk-field">
            <label className="tmk-field__label" htmlFor="cvReference">مرجع السيرة الذاتية</label>
            <span className="tmk-field__hint" id="cv-hint">
              رفع الملفات لم يُبنَ بعد (PER-10.A02): اكتب هنا اسم المستند أو رابطه لدى جهة أخرى، ولا يُرفع شيء إلى المنصة.
            </span>
            <input id="cvReference" name="cvReference" className="tmk-field__control" defaultValue={profile.cvReference} maxLength={200} aria-describedby="cv-hint" />
          </div>

          <fieldset className="tmk-fieldset">
            <legend>المشاركة</legend>
            <label className="tmk-choice" htmlFor="shareWithOperators">
              <input id="shareWithOperators" name="shareWithOperators" type="checkbox" defaultChecked={profile.shareWithOperators} />
              <span>أوافق على مشاركة هذا الملف مع الجهة المشغّلة للبرامج التي أتقدم إليها.</span>
            </label>
            <label className="tmk-choice" htmlFor="shareContact">
              <input id="shareContact" name="shareContact" type="checkbox" defaultChecked={profile.shareContact} />
              <span>أوافق أيضًا على مشاركة بريدي الإلكتروني معها.</span>
            </label>
            <p className="tmk-field__hint">
              الموافقتان منفصلتان، والثانية لا تسري بدون الأولى. سحب الأولى يخفي الملف عن كل جهة فورًا، بما فيها طلبات قائمة.
            </p>
          </fieldset>

          <p className="tmk-row__actions">
            <button type="submit" className="tmk-button tmk-button--primary" disabled={busy}>احفظ الملف</button>
            <button type="button" className="tmk-button tmk-button--secondary" disabled={busy}
              onClick={() => void (async () => {
                setBusy(true); setError('');
                try { setPreview(await api('/me/candidate-profile/employer-preview') as typeof preview); }
                catch (e) { setError(e instanceof Error ? e.message : 'تعذر عرض المعاينة.'); }
                finally { setBusy(false); }
              })()}>
              ماذا ترى الجهة المشغّلة؟
            </button>
          </p>
        </form>
      </Card>

      {/* PER-10.A03. Generated by the server from the same allowlist the operator reads.
          The heading changes with the consent, because a list of fields under the words "this is
          what they receive" is false while the consent is off — and a candidate deciding whether
          to turn it on still needs to see what turning it on would send. */}
      {preview ? (
        <Card title={preview.shared ? 'ما تستلمه الجهة المشغّلة الآن' : 'ما ستشاركه إن وافقت'}>
          <p className="tmk-field__hint">
            {preview.shared
              ? 'هذه ليست محاكاة: الخادم يبنيها بالدالة نفسها التي تبني قراءة الجهة، فما تراه هنا هو ما تستلمه هي بالضبط.'
              : 'الخادم يبنيها بالدالة نفسها التي تبني قراءة الجهة، فهذه هي الحقول التي ستخرج من حسابك لو فعّلت الموافقة — ولا تخرج الآن.'}
          </p>
          {!preview.shared ? (
            <Notice tone="warning" title="لا تُشارك شيئًا الآن">
              <p style={{ marginBlockEnd: 0 }}>
                لم توافق على المشاركة، فلا ترى الجهة المشغّلة أي جزء من ملفك. ما يظهر أدناه معاينة لما سيخرج لو وافقت، لا لما خرج.
              </p>
            </Notice>
          ) : null}
          <dl className="tmk-definitions">
            {Object.entries(preview.profile).map(([key, value]) => (
              <div key={key}>
                <dt>{key}</dt>
                <dd>{value === null ? <span className="tmk-field__hint">محجوب</span> : Array.isArray(value) ? value.join('، ') : String(value)}</dd>
              </div>
            ))}
          </dl>
          <p className="tmk-field__hint">
            لا يُرسل أبدًا: {preview.withheld.join('، ')}. هذه ليست حقولًا فارغة، بل حقول لا تخرج من حسابك أصلًا.
          </p>
        </Card>
      ) : null}

      <p className="tmk-row__actions">
        <a className="tmk-button tmk-button--secondary" href={L('/opportunities')}>اكتشف البرامج</a>
        <a className="tmk-button tmk-button--quiet" href={L('/app/applications')}>طلباتي</a>
      </p>
    </>
  );
}

// ---------------------------------------------------------------------------------------------
// PER-11 / PER-12 — applying, and following an application
// ---------------------------------------------------------------------------------------------

interface MyApplication {
  id: string; reference: string; state: string; motivation: string; sharingConsent: boolean;
  submittedAt: string | null; decidedAt: string | null; withdrawnReason: string; version: number;
  programSlug: string; programTitle: string; operator: string;
  cohort: { id: string; name: string; startAt: string; endAt: string; timezone: string };
  interviews: Array<{ id: string; scheduledAt: string; durationMinutes: number; timezone: string; mode: string; location: string; state: string; version: number }>;
  enrollment: { id: string; state: string; invitationExpiresAt: string; confirmedAt: string | null; version: number; acceptable: boolean } | null;
  waitlistPosition: number | null;
  latestDecision: { outcome: string; reason: string; at: string } | null;
  trainingIsNotEmployment: boolean;
}

export function MyApplications({ locale, applicationId, mode }: { locale: Locale; applicationId?: string; mode: 'list' | 'new' | 'detail' | 'edit' }) {
  const L = (path: string) => localePath(locale, path);
  const t = translator(locale);
  const [rows, setRows] = useState<MyApplication[] | null>(null);
  const [detail, setDetail] = useState<(MyApplication & { program: { withdrawalPolicy: string; attendancePolicy: string; complaintsContact: string }; decisions: Array<{ id: string; outcome: string; reason: string; at: string }> }) | null>(null);
  const [program, setProgram] = useState<{ title: string; slug: string; acceptsApplications: boolean; applicationsUnavailableReason: string; cohorts: Array<{ id: string; name: string; startAt: string; seatsRemaining: number }> } | null>(null);
  const [draft, setDraft] = useState<MyApplication | null>(null);
  const [signedIn, setSignedIn] = useState(true);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');

  const load = useCallback(async () => {
    if (mode === 'list') { setRows(await api('/me/applications') as MyApplication[]); return; }
    if (mode === 'new') {
      const slug = new URLSearchParams(window.location.search).get('program');
      if (!slug) throw new Error('لم يُحدَّد البرنامج.');
      setProgram(await api(`/programs/${encodeURIComponent(slug)}`) as typeof program);
      return;
    }
    if (applicationId) setDetail(await api(`/me/applications/${applicationId}`) as typeof detail);
  }, [mode, applicationId]);

  useEffect(() => {
    let active = true;
    (async () => {
      try { await load(); }
      catch (e) {
        if (!active) return;
        if (e instanceof UnauthenticatedError) setSignedIn(false);
        else setError(e instanceof Error ? e.message : 'تعذر التحميل.');
      }
      finally { if (active) setLoading(false); }
    })();
    return () => { active = false; };
  }, [load]);

  const run = async (action: () => Promise<string>) => {
    if (busy) return;
    setBusy(true); setError(''); setNotice('');
    try { setNotice(await action()); await load(); }
    catch (e) { setError(e instanceof Error ? e.message : 'تعذر إكمال العملية.'); }
    finally { setBusy(false); }
  };

  const shell = (children: ReactNode) => (
    <AppShell locale={locale} path="/app/applications" signedIn={signedIn}
      userActions={<a className="tmk-button tmk-button--quiet" href={L('/app/applications')}>طلباتي</a>}>
      {error ? <Notice tone="danger" live="assertive">{error}</Notice> : null}
      {notice ? <Notice tone="success" live="polite">{notice}</Notice> : null}
      {children}
    </AppShell>
  );

  if (loading) return shell(<Skeleton lines={6} label={t('loading')} />);
  if (!signedIn) {
    return shell(
      <ErrorState title={t('forbiddenTitle')} onRetry={<a className="tmk-button tmk-button--primary" href={`${L('/login')}?returnTo=${encodeURIComponent(L('/app/applications'))}`}>{t('signIn')}</a>}>
        الطلب يُنسب إلى شخص بعينه، فيحتاج حسابًا.
      </ErrorState>
    );
  }

  // ---- PER-11: a new application ------------------------------------------------------------------
  if (mode === 'new') {
    if (!program) return shell(<ErrorState title="غير موجود">هذا البرنامج غير متاح للتقديم.</ErrorState>);
    return shell(
      <>
        <PageHeader dashboard eyebrow={program.title} title="طلب جديد" lead="احفظ مسودة ثم أرسلها. المسودة لا يراها أحد غيرك، ولا تُنشئ مقعدًا." />
        <NotEmployment />
        {!program.acceptsApplications ? (
          <Notice tone="warning" title="التقديم مغلق">
            <p style={{ marginBlockEnd: 0 }}>لم يعد هذا البرنامج يقبل طلبات ({program.applicationsUnavailableReason}).</p>
          </Notice>
        ) : draft ? (
          <Card title="المسودة محفوظة">
            <p>رقم طلبك: <code><Ltr>{draft.reference}</Ltr></code></p>
            <p className="tmk-row__actions">
              <a className="tmk-button tmk-button--primary" href={L(`/app/applications/${draft.id}/edit`)}>أكمل الطلب</a>
              <a className="tmk-button tmk-button--quiet" href={L('/app/applications')}>طلباتي</a>
            </p>
          </Card>
        ) : (
          <Card title="اختر الدفعة واكتب دافعك">
            <form onSubmit={event => {
              event.preventDefault();
              const form = new FormData(event.currentTarget);
              void run(async () => {
                const created = await api('/applications', 'POST', {
                  cohortId: String(form.get('cohortId') ?? ''),
                  motivation: String(form.get('motivation') ?? '')
                }) as MyApplication;
                setDraft(created);
                return 'حُفظت المسودة. لم تُرسل بعد، ولم يطّلع عليها أحد.';
              });
            }}>
              <div className="tmk-field">
                <label className="tmk-field__label" htmlFor="cohortId">الدفعة</label>
                <select id="cohortId" name="cohortId" className="tmk-field__control" required>
                  {program.cohorts.map(cohort => (
                    <option key={cohort.id} value={cohort.id}>
                      {cohort.name} — يبدأ {formatDate(cohort.startAt, locale)} · مقاعد متبقية {cohort.seatsRemaining}
                    </option>
                  ))}
                </select>
              </div>
              <div className="tmk-field">
                <label className="tmk-field__label" htmlFor="motivation">لماذا تتقدم لهذا البرنامج؟</label>
                <textarea id="motivation" name="motivation" className="tmk-field__control" rows={6} maxLength={4000} required />
              </div>
              <button type="submit" className="tmk-button tmk-button--primary" disabled={busy}>احفظ المسودة</button>
            </form>
          </Card>
        )}
      </>
    );
  }

  // ---- PER-11 edit / PER-12 detail ---------------------------------------------------------------
  if (mode === 'detail' || mode === 'edit') {
    if (!detail) return shell(<ErrorState title="غير موجود">هذا الطلب غير موجود ضمن سجلك.</ErrorState>);
    const state = applicationStates[detail.state] ?? { text: detail.state, tone: 'neutral' as Tone };
    return shell(
      <>
        <PageHeader
          dashboard
          eyebrow={`${detail.operator} · ${detail.programTitle}`}
          title={`طلب ${detail.reference}`}
          lead="كل خطوة على حدة: الإرسال، والفرز، والمقابلة، والقرار، ثم قبولك للمقعد."
          actions={<StatusBadge tone={state.tone}>{state.text}</StatusBadge>}
        />
        <NotEmployment />

        {/* PER-11.A03. What the reviewer actually receives, assembled from the same two pieces the
            server sends: the answers on this form, and the profile under its own consent. */}
        {detail.state === 'draft' ? (
          <Card title="معاينة ما سيستلمه المراجع">
            <p className="tmk-field__hint">
              يستلم المراجع شيئين فقط: نص دافعك أدناه، وملف مهاراتك إن وافقت على مشاركته. لا يصله شيء آخر من حسابك.
            </p>
            <dl className="tmk-definitions">
              <div><dt>رقم الطلب</dt><dd><code><Ltr>{detail.reference}</Ltr></code></dd></div>
              <div><dt>الدفعة</dt><dd>{detail.cohort.name}</dd></div>
              <div><dt>دافع التقديم</dt><dd>{detail.motivation || <span className="tmk-field__hint">لم يُكتب بعد</span>}</dd></div>
            </dl>
            <p className="tmk-row__actions">
              <a className="tmk-button tmk-button--quiet" href={L('/app/career/profile')}>اعرض ملفك كما تراه الجهة</a>
            </p>
          </Card>
        ) : null}

        {detail.state === 'draft' ? (
          <Card title="أكمل الطلب وأرسله">
            <form onSubmit={event => {
              event.preventDefault();
              const form = new FormData(event.currentTarget);
              const consent = form.get('sharingConsent') === 'on';
              void run(async () => {
                // Named before the request, so the answer is the one thing that is missing rather
                // than a general list of everything this endpoint can refuse.
                if (!consent) throw new Error('الموافقة على مشاركة ملفك شرط للإرسال: بدونها لا تستطيع الجهة تقييم طلبك أصلًا.');
                await api('/applications', 'POST', { cohortId: detail.cohort.id, applicationId: detail.id, motivation: String(form.get('motivation') ?? ''), version: detail.version });
                const refreshed = await api(`/me/applications/${detail.id}`) as typeof detail;
                await api(`/applications/${detail.id}/submit`, 'POST', { sharingConsent: consent, version: refreshed!.version });
                return `أُرسل الطلب برقم ${detail.reference}. الموعد النهائي يُفحص لحظة الإرسال، وقد وصل قبله.`;
              });
            }}>
              <div className="tmk-field">
                <label className="tmk-field__label" htmlFor="motivation">لماذا تتقدم لهذا البرنامج؟</label>
                <textarea id="motivation" name="motivation" className="tmk-field__control" rows={6} defaultValue={detail.motivation} maxLength={4000} required />
              </div>
              <label className="tmk-choice" htmlFor="sharingConsent">
                <input id="sharingConsent" name="sharingConsent" type="checkbox" />
                <span>أوافق على مشاركة ملف مهاراتي مع هذه الجهة المشغّلة لغرض هذا الطلب.</span>
              </label>
              <p className="tmk-field__hint">
                بدون هذه الموافقة لا يمكن تقييم طلبك أصلًا، فهي شرط للإرسال لا خيار بعده. يمكنك سحبها لاحقًا من ملف المهارات.
              </p>
              <p className="tmk-row__actions">
                <button type="submit" className="tmk-button tmk-button--primary" disabled={busy}>أرسل الطلب</button>
                <button type="button" className="tmk-button tmk-button--quiet" disabled={busy}
                  onClick={() => void run(async () => {
                    await api(`/applications/${detail.id}/discard`, 'POST', { version: detail.version });
                    return 'أُلغيت المسودة. لم يرها أحد.';
                  })}>
                  ألغِ المسودة
                </button>
              </p>
            </form>
          </Card>
        ) : null}

        <Card title="مسار الطلب">
          <dl className="tmk-definitions">
            <div><dt>الدفعة</dt><dd>{detail.cohort.name} — {formatDate(detail.cohort.startAt, locale)} (<Ltr>{detail.cohort.timezone}</Ltr>)</dd></div>
            <div><dt>أُرسل</dt><dd>{detail.submittedAt ? formatDate(detail.submittedAt, locale, true) : '—'}</dd></div>
            <div><dt>القرار</dt><dd>{detail.decidedAt ? formatDate(detail.decidedAt, locale, true) : <span className="tmk-field__hint">لم يصدر بعد</span>}</dd></div>
            {detail.waitlistPosition ? <div><dt>موقعك في قائمة الانتظار</dt><dd><Ltr>{String(detail.waitlistPosition)}</Ltr></dd></div> : null}
          </dl>
          {detail.decisions.length > 0 ? (
            <ul>
              {detail.decisions.map(decision => (
                <li key={decision.id}>
                  <strong>{applicationStates[decision.outcome]?.text ?? decision.outcome}</strong>
                  {decision.reason ? ` — ${decision.reason}` : ''} <span className="tmk-field__hint">{formatDate(decision.at, locale)}</span>
                </li>
              ))}
            </ul>
          ) : null}
        </Card>

        {detail.interviews.length > 0 ? (
          <Card title="المقابلات">
            {detail.interviews.map(interview => (
              <article className="tmk-row" key={interview.id}>
                <div>
                  <strong>{formatDate(interview.scheduledAt, locale, true)}</strong>
                  <p className="tmk-field__hint">
                    <Ltr>{interview.timezone}</Ltr> · {interview.durationMinutes} دقيقة · {interview.mode === 'remote' ? 'عن بعد' : interview.location}
                  </p>
                  <p className="tmk-field__hint">
                    <StatusBadge tone={interviewStates[interview.state]?.tone ?? 'neutral'}>
                      {interviewStates[interview.state]?.text ?? interview.state}
                    </StatusBadge>
                  </p>
                </div>
                <span className="tmk-row__actions">
                  {['proposed', 'reschedule_requested'].includes(interview.state) ? (
                    <button type="button" className="tmk-button tmk-button--primary" disabled={busy}
                      onClick={() => void run(async () => {
                        await api(`/interviews/${interview.id}/confirm`, 'POST', { version: interview.version });
                        return 'أكّدت الموعد.';
                      })}>
                      أكّد الموعد
                    </button>
                  ) : null}
                  {interview.state !== 'cancelled' ? (
                    <button type="button" className="tmk-button tmk-button--quiet" disabled={busy}
                      onClick={() => void run(async () => {
                        const why = window.prompt('سبب طلب تغيير الموعد (عشرة أحرف على الأقل):') ?? '';
                        if (why.trim().length < 10) throw new Error('السبب مطلوب ولا يقل عن عشرة أحرف.');
                        const alternatives = window.prompt('بدائل تناسبك (اختياري):') ?? '';
                        await api(`/interviews/${interview.id}/reschedule-requests`, 'POST', { reason: why, alternatives });
                        return 'أُرسل طلب تغيير الموعد. الموعد الأصلي ما زال قائمًا حتى ترد الجهة، فلا تعتبره ملغى.';
                      })}>
                      اطلب تغيير الموعد
                    </button>
                  ) : null}
                </span>
              </article>
            ))}
            <p className="tmk-field__hint">
              كل موعد يحمل منطقته الزمنية. طلب التغيير طلب لا تعديل: الموعد لا يتحرك قبل رد الجهة.
            </p>
          </Card>
        ) : null}

        {detail.enrollment ? (
          <Card title="المقعد">
            <div className="tmk-grid tmk-grid--stats">
              <Stat label="الحالة" value={enrollmentStates[detail.enrollment.state]?.text ?? detail.enrollment.state} />
              <Stat label="تنتهي المهلة" value={formatDate(detail.enrollment.invitationExpiresAt, locale, true)} note="بعدها يتحرر المقعد للتالي في قائمة الانتظار." />
            </div>
            {detail.enrollment.acceptable ? (
              <p className="tmk-row__actions">
                <button type="button" className="tmk-button tmk-button--primary" disabled={busy}
                  onClick={() => void run(async () => {
                    await api(`/enrollments/${detail.enrollment!.id}/accept`, 'POST', { version: detail.enrollment!.version });
                    return 'قبلت المقعد. هذا التحاق بتدريب، وليس عقد عمل.';
                  })}>
                  اقبل المقعد
                </button>
              </p>
            ) : detail.enrollment.state === 'invited' ? (
              <Notice tone="warning" title="انتهت المهلة">
                <p style={{ marginBlockEnd: 0 }}>مضت مهلة قبول المقعد، فتحرر لغيرك. لا يمكن قبوله متأخرًا.</p>
              </Notice>
            ) : null}
            {detail.enrollment.state === 'confirmed' || detail.enrollment.state === 'active' ? (
              <p className="tmk-row__actions">
                <a className="tmk-button tmk-button--secondary" href={L(`/app/training/${detail.enrollment.id}`)}>افتح تدريبي</a>
              </p>
            ) : null}
          </Card>
        ) : null}

        {['submitted', 'screening', 'shortlisted', 'interview', 'waitlisted', 'accepted'].includes(detail.state) ? (
          <Card title="سحب الطلب">
            <p className="tmk-field__hint">السحب يحرر المقعد أو الدور إن كان محجوزًا، ويبقي أثر ما حدث في سجلك.</p>
            <button type="button" className="tmk-button tmk-button--quiet" disabled={busy}
              onClick={() => void run(async () => {
                const why = window.prompt('سبب السحب (عشرة أحرف على الأقل):') ?? '';
                if (why.trim().length < 10) throw new Error('السبب مطلوب ولا يقل عن عشرة أحرف.');
                await api(`/applications/${detail.id}/withdraw`, 'POST', { reason: why, version: detail.version });
                return 'سُحب الطلب وتحرر ما كان محجوزًا.';
              })}>
              اسحب الطلب
            </button>
          </Card>
        ) : null}

        <Card title="سياسات تخصك">
          <div className="tmk-prose">
            <h3>الانسحاب</h3><p>{detail.program.withdrawalPolicy}</p>
            <h3>الحضور</h3><p>{detail.program.attendancePolicy}</p>
          </div>
          {detail.program.complaintsContact ? <p className="tmk-field__hint">مسؤول الشكاوى: <bdi>{detail.program.complaintsContact}</bdi></p> : null}
        </Card>
      </>
    );
  }

  // ---- PER-12: the list ---------------------------------------------------------------------------
  return shell(
    <>
      <PageHeader dashboard title="طلباتي" lead="كل طلب وحالته الحقيقية: المسودة ليست إرسالًا، والقبول ليس مقعدًا حتى تقبله، والمقعد ليس وظيفة." />
      <NotEmployment />
      <Card title="الطلبات">
        <DataTable
          caption="طلباتك، أحدثها أولًا"
          rows={rows ?? []}
          rowKey={row => row.id}
          emptyState={
            <EmptyState title="لا طلبات بعد" action={<a className="tmk-button tmk-button--primary" href={L('/opportunities')}>اكتشف البرامج</a>}>
              لم تتقدم لأي برنامج حتى الآن. حفظ برنامج في قائمتك لا يُنشئ طلبًا.
            </EmptyState>
          }
          columns={[
            { key: 'program', header: 'البرنامج', cell: row => <><a href={L(`/programs/${row.programSlug}`)}>{row.programTitle}</a><span className="tmk-field__hint">{row.operator}</span></> },
            { key: 'reference', header: 'الرقم', cell: row => <code><Ltr>{row.reference}</Ltr></code> },
            { key: 'cohort', header: 'الدفعة', cell: row => row.cohort.name },
            { key: 'state', header: 'الحالة', cell: row => <StatusBadge tone={applicationStates[row.state]?.tone ?? 'neutral'}>{applicationStates[row.state]?.text ?? row.state}</StatusBadge> },
            {
              key: 'seat', header: 'المقعد',
              cell: row => row.enrollment
                ? <>{enrollmentStates[row.enrollment.state]?.text ?? row.enrollment.state}{row.enrollment.acceptable ? <span className="tmk-field__hint">تنتهي المهلة {formatDate(row.enrollment.invitationExpiresAt, locale, true)}</span> : null}</>
                : row.waitlistPosition ? <>قائمة انتظار — الدور <Ltr>{String(row.waitlistPosition)}</Ltr></> : <span className="tmk-field__hint">—</span>
            },
            { key: 'open', header: '', cell: row => <a href={L(`/app/applications/${row.id}`)}>{row.state === 'draft' ? 'أكمل' : 'افتح'}</a> }
          ]}
        />
      </Card>
    </>
  );
}

// ---------------------------------------------------------------------------------------------
// PER-13 — my training
// ---------------------------------------------------------------------------------------------

interface MyTrainingData {
  enrollment: { id: string; state: string; confirmedAt: string | null; exitReason: string; version: number };
  cohort: { id: string; name: string; startAt: string; endAt: string; timezone: string };
  program: { id: string; title: string; slug: string; attendancePolicy: string; assessmentPolicy: string; withdrawalPolicy: string; complaintsContact: string; operator: string };
  sessions: Array<{
    id: string; title: string; startsAt: string; endsAt: string; timezone: string; location: string; state: string;
    attendance: { id: string; status: string; excuseNote: string; recordedAt: string } | null;
    objection: { id: string; state: string; reason: string; decisionReason: string } | null;
    canObject: boolean;
  }>;
  attendanceSummary: { recorded: number; counted: number; present: number; late: number; excused: number; absent: number; policy: string };
  results: Array<{ id: string; title: string; total: number; scaleMax: number; passMark: number; passed: boolean; at: string }>;
  withdrawalRequests: Array<{ id: string; reason: string; state: string; decisionReason: string; createdAt: string }>;
  stipends: { available: boolean; reason: string; offeredByProgram: boolean; conditions: string };
  certificate: { available: boolean; reason: string };
}

export function MyTrainingScreen({ locale, enrollmentId }: { locale: Locale; enrollmentId: string }) {
  const L = (path: string) => localePath(locale, path);
  const t = translator(locale);
  const [data, setData] = useState<MyTrainingData | null>(null);
  const [signedIn, setSignedIn] = useState(true);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');

  const load = useCallback(async () => setData(await api(`/me/training/${enrollmentId}`) as MyTrainingData), [enrollmentId]);

  useEffect(() => {
    let active = true;
    (async () => {
      try { await load(); }
      catch (e) {
        if (!active) return;
        if (e instanceof UnauthenticatedError) setSignedIn(false);
        else setError(e instanceof Error ? e.message : 'تعذر تحميل التدريب.');
      }
      finally { if (active) setLoading(false); }
    })();
    return () => { active = false; };
  }, [load]);

  const run = async (action: () => Promise<string>) => {
    if (busy) return;
    setBusy(true); setError(''); setNotice('');
    try { setNotice(await action()); await load(); }
    catch (e) { setError(e instanceof Error ? e.message : 'تعذر إكمال العملية.'); }
    finally { setBusy(false); }
  };

  const shell = (children: ReactNode) => (
    <AppShell locale={locale} path="/app/applications" signedIn={signedIn}
      userActions={<a className="tmk-button tmk-button--quiet" href={L('/app/applications')}>طلباتي</a>}>
      {error ? <Notice tone="danger" live="assertive">{error}</Notice> : null}
      {notice ? <Notice tone="success" live="polite">{notice}</Notice> : null}
      {children}
    </AppShell>
  );

  if (loading) return shell(<Skeleton lines={6} label={t('loading')} />);
  if (!signedIn) return shell(<ErrorState title={t('forbiddenTitle')} onRetry={<a className="tmk-button tmk-button--primary" href={L('/login')}>{t('signIn')}</a>}>{t('forbiddenBody')}</ErrorState>);
  if (!data) return shell(<ErrorState title="غير موجود">هذا التدريب غير موجود ضمن سجلك.</ErrorState>);

  return shell(
    <>
      <PageHeader
        dashboard
        eyebrow={`${data.program.operator} · ${data.cohort.name}`}
        title={data.program.title}
        lead="جدولك وسجل حضورك ونتائجك، وبجوارها القاعدة التي ستُقرأ بها."
        actions={<StatusBadge tone={enrollmentStates[data.enrollment.state]?.tone ?? 'neutral'}>{enrollmentStates[data.enrollment.state]?.text ?? data.enrollment.state}</StatusBadge>}
      />
      <NotEmployment />

      <div className="tmk-grid tmk-grid--stats">
        <Stat label="جلسات مسجَّلة" value={<Ltr>{String(data.attendanceSummary.recorded)}</Ltr>} />
        <Stat label="محتسبة لك" value={<Ltr>{String(data.attendanceSummary.counted)}</Ltr>} note="حضور أو تأخر أو غياب بعذر." />
        <Stat label="غياب بلا عذر" value={<Ltr>{String(data.attendanceSummary.absent)}</Ltr>} />
      </div>
      <Notice tone="info" title="القاعدة التي تُقرأ بها هذه الأرقام">
        <p style={{ marginBlockEnd: 0 }}>{data.attendanceSummary.policy}</p>
      </Notice>

      <Card title="الجلسات">
        <DataTable
          caption="جلسات دفعتك"
          rows={data.sessions}
          rowKey={session => session.id}
          emptyState={<EmptyState title="لا جلسات بعد">لم تُجدول جلسات لهذه الدفعة حتى الآن.</EmptyState>}
          columns={[
            { key: 'title', header: 'الجلسة', cell: session => <>{session.title}<span className="tmk-field__hint">{session.location}</span></> },
            { key: 'when', header: 'الموعد', cell: session => <>{formatDate(session.startsAt, locale, true)}<span className="tmk-field__hint"><Ltr>{session.timezone}</Ltr></span></> },
            {
              key: 'attendance', header: 'حضورك',
              cell: session => session.attendance
                ? <>
                    <StatusBadge tone={attendanceLabels[session.attendance.status]?.tone ?? 'neutral'}>{attendanceLabels[session.attendance.status]?.text ?? session.attendance.status}</StatusBadge>
                    {session.attendance.excuseNote ? <span className="tmk-field__hint">{session.attendance.excuseNote}</span> : null}
                  </>
                : <span className="tmk-field__hint">لم يُسجَّل</span>
            },
            {
              key: 'objection', header: 'الاعتراض',
              cell: session => session.objection
                ? <>{session.objection.state === 'open' ? 'قيد المراجعة' : session.objection.state === 'upheld' ? 'قُبل الاعتراض' : 'رُفض الاعتراض'}
                    {session.objection.decisionReason ? <span className="tmk-field__hint">{session.objection.decisionReason}</span> : null}</>
                : session.canObject
                  ? <button type="button" className="tmk-button tmk-button--quiet" disabled={busy}
                      onClick={() => void run(async () => {
                        const why = window.prompt('سبب الاعتراض (عشرة أحرف على الأقل):') ?? '';
                        if (why.trim().length < 10) throw new Error('السبب مطلوب ولا يقل عن عشرة أحرف.');
                        await api(`/attendance/${session.attendance!.id}/objections`, 'POST', { reason: why });
                        return 'سُجِّل اعتراضك. السجل لا يتغير قبل أن يبتّ فيه شخص غير من سجّله.';
                      })}>
                      اعترض
                    </button>
                  : <span className="tmk-field__hint">—</span>
            }
          ]}
        />
        <p className="tmk-field__hint">
          الاعتراض لا يعدّل السجل بنفسه. يراجعه شخص آخر غير من سجّله، وإن قُبل يُصحَّح بمراجعة مكتوبة تبقى في السجل.
        </p>
      </Card>

      {data.results.length > 0 ? (
        <Card title="نتائج التقييم">
          <DataTable
            caption="نتائجك"
            rows={data.results}
            rowKey={result => result.id}
            emptyState={<EmptyState title="لا نتائج" />}
            columns={[
              { key: 'title', header: 'التقييم', cell: result => result.title },
              { key: 'total', header: 'الدرجة', numeric: true, cell: result => <Ltr>{String(result.total)}</Ltr> },
              { key: 'pass', header: 'النتيجة', cell: result => <StatusBadge tone={result.passed ? 'success' : 'danger'}>{result.passed ? 'اجتياز' : 'دون حد الاجتياز'}</StatusBadge> },
              { key: 'at', header: 'التاريخ', cell: result => formatDate(result.at, locale) }
            ]}
          />
        </Card>
      ) : null}

      <Card title="الانسحاب">
        <div className="tmk-prose"><p>{data.program.withdrawalPolicy}</p></div>
        {data.withdrawalRequests.length > 0 ? (
          <ul>
            {data.withdrawalRequests.map(request => (
              <li key={request.id}>
                {request.state === 'open' ? 'قيد التقييم' : request.state === 'upheld' ? 'قُبل' : 'رُفض'} — {request.reason}
                {request.decisionReason ? <span className="tmk-field__hint">{request.decisionReason}</span> : null}
              </li>
            ))}
          </ul>
        ) : null}
        {['confirmed', 'active'].includes(data.enrollment.state) && !data.withdrawalRequests.some(request => request.state === 'open') ? (
          <button type="button" className="tmk-button tmk-button--quiet" disabled={busy}
            onClick={() => void run(async () => {
              const why = window.prompt('سبب طلب الانسحاب (عشرة أحرف على الأقل):') ?? '';
              if (why.trim().length < 10) throw new Error('السبب مطلوب ولا يقل عن عشرة أحرف.');
              await api(`/enrollments/${enrollmentId}/withdrawal-requests`, 'POST', { reason: why });
              return 'أُرسل طلب الانسحاب. لم يتغير التحاقك بعد: الجهة تقيّمه وفق السياسة المعلنة أعلاه.';
            })}>
            اطلب الانسحاب
          </button>
        ) : null}
      </Card>

      {/* PER-13.A03/A04: declared, not offered. */}
      <Card title="ما لا تستطيع هذه الصفحة فعله بعد">
        <ul>
          <li>
            <strong>البدلات.</strong> {data.stipends.offeredByProgram ? `يعلن البرنامج بدلًا (${data.stipends.conditions || 'بشروطه المعلنة'})، ` : 'لا يعلن هذا البرنامج بدلًا، و'}
            احتساب الاستحقاق وصرفه لم يُبنَ بعد، فلا يُعرض رقم استحقاق قد يُقرأ كوعد.
          </li>
          <li>
            <strong>الشهادة.</strong> إصدار الشهادات ومرجع تحققها العام لم يُبنَ بعد، فلا يوجد زر تنزيل.
          </li>
        </ul>
      </Card>
    </>
  );
}
