import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { test } from 'node:test';
import { CURRENT_TERMS_VERSION, loadConfig } from '@tamkeen/config';
import { createDatabase } from '@tamkeen/database';
import { IdentityService } from '../apps/api/dist/modules/identity/identity.service.js';

const config = loadConfig(process.env);
test('identity, party, tenant isolation, invitation races and owner invariants on PostgreSQL', async () => {
  const db = createDatabase(config.databaseUrl);
  const service = new IdentityService(db);
  const prefix = randomUUID();
  const users: string[] = [];
  const organizations: string[] = [];
  const createUser = async (suffix: string, verified = true) => {
    const user = await db.user.create({ data: { email: `${prefix}-${suffix}@example.test`, name: `Test ${suffix}`, emailVerified: verified, termsVersion: CURRENT_TERMS_VERSION, termsAcceptedAt: new Date() } });
    users.push(user.id);
    return user;
  };
  try {
    const ownerA = await createUser('owner-a');
    const ownerB = await createUser('owner-b');
    const invited = await createUser('invited');
    const revokedInvitee = await createUser('revoked-invitee');
    const declinedInvitee = await createUser('declined-invitee');
    const raceInvitee = await createUser('race-invitee');
    const unverified = await createUser('unverified', false);
    const reviewer = await createUser('reviewer');
    const platformAdmin = await createUser('platform-admin');
    const platformStaff = await createUser('platform-staff');
    const newOwner = await createUser('new-owner');
    await db.user.update({ where: { id: reviewer.id }, data: { twoFactorEnabled: true } });
    await db.user.update({ where: { id: platformAdmin.id }, data: { twoFactorEnabled: true } });
    await db.platformGrant.create({ data: { userId: platformAdmin.id, role: 'PlatformAdmin', grantedBy: platformAdmin.id } });
    const reviewerSession = await db.session.create({ data: { userId: reviewer.id, token: 'c'.repeat(64), expiresAt: new Date(Date.now() + 3600_000) } });
    const ownerCurrentSession = await db.session.create({ data: { userId: ownerA.id, token: 'd'.repeat(64), expiresAt: new Date(Date.now() + 3600_000), ipAddress: '127.0.0.1', userAgent: 'Test current browser' } });
    const ownerOtherSession = await db.session.create({ data: { userId: ownerA.id, token: 'e'.repeat(64), expiresAt: new Date(Date.now() + 3600_000), ipAddress: '192.0.2.10', userAgent: 'Test other browser' } });
    const foreignSession = await db.session.create({ data: { userId: ownerB.id, token: 'f'.repeat(64), expiresAt: new Date(Date.now() + 3600_000) } });
    const sessionList = await service.accountSessions(ownerA.id, ownerCurrentSession.id);
    assert.equal(sessionList.length, 2);
    assert.equal(sessionList.find(item => item.id === ownerCurrentSession.id)?.current, true);
    assert.equal(Object.hasOwn(sessionList[0] ?? {}, 'token'), false);
    await assert.rejects(() => service.revokeSession(ownerA.id, ownerCurrentSession.id, foreignSession.id));
    assert.ok(await db.session.findUnique({ where: { id: foreignSession.id } }));
    assert.equal((await service.revokeSession(ownerA.id, ownerCurrentSession.id, ownerOtherSession.id)).current, false);
    assert.equal((await service.revokeSession(ownerA.id, ownerCurrentSession.id, ownerCurrentSession.id)).current, true);
    assert.equal((await service.accountSessions(ownerA.id, ownerCurrentSession.id)).length, 0);
    await assert.rejects(() => service.invitePlatformStaff(reviewer.id, { email: platformStaff.email, roles: ['VerificationReviewer'], grantExpiresAt: new Date(Date.now() + 30 * 24 * 3600_000) }, config.appBaseUrl));
    await assert.rejects(() => service.invitePlatformStaff(platformAdmin.id, { email: platformStaff.email, roles: ['Auditor', 'Support'], grantExpiresAt: new Date(Date.now() + 30 * 24 * 3600_000) }, config.appBaseUrl));
    const staffInvitation = await service.invitePlatformStaff(platformAdmin.id, { email: platformStaff.email.toUpperCase(), roles: ['VerificationReviewer'], grantExpiresAt: new Date(Date.now() + 30 * 24 * 3600_000) }, config.appBaseUrl);
    assert.equal(await db.localAuthMail.count({ where: { recipient: platformStaff.email, purpose: 'platform-invitation' } }), 1);
    const staffMail = await db.localAuthMail.findFirstOrThrow({ where: { recipient: platformStaff.email, purpose: 'platform-invitation' }, orderBy: { createdAt: 'desc' } });
    const staffToken = staffMail.url.split('/').at(-1) ?? '';
    assert.equal((await service.platformInvitationPreview(platformStaff.id, staffToken)).requiresMfaSetup, true);
    await assert.rejects(() => service.platformInvitationPreview(ownerB.id, staffToken));
    await assert.rejects(() => service.acceptPlatformInvitation(platformStaff.id, staffToken));
    await db.user.update({ where: { id: platformStaff.id }, data: { twoFactorEnabled: true } });
    assert.equal((await service.acceptPlatformInvitation(platformStaff.id, staffToken)).status, 'accepted');
    await assert.rejects(() => service.acceptPlatformInvitation(platformStaff.id, staffToken));
    assert.deepEqual(await service.platformRoles(platformStaff.id), ['VerificationReviewer']);
    const teamAfterAccept = await service.platformTeam(platformAdmin.id);
    const acceptedStaff = teamAfterAccept.members.find(member => member.user.id === platformStaff.id);
    assert.ok(acceptedStaff);
    assert.equal(acceptedStaff.user.platformAccessVersion, 2);
    await db.session.create({ data: { userId: platformStaff.id, token: 'g'.repeat(64), expiresAt: new Date(Date.now() + 3600_000) } });
    const replaced = await service.replacePlatformGrants(platformAdmin.id, platformStaff.id, { roles: ['ContentReviewer'], expiresAt: new Date(Date.now() + 20 * 24 * 3600_000), version: acceptedStaff.user.platformAccessVersion });
    assert.deepEqual(await service.platformRoles(platformStaff.id), ['ContentReviewer']);
    assert.equal(await db.session.count({ where: { userId: platformStaff.id } }), 0);
    await assert.rejects(() => service.replacePlatformGrants(platformAdmin.id, platformStaff.id, { roles: ['Support'], expiresAt: new Date(Date.now() + 20 * 24 * 3600_000), version: acceptedStaff.user.platformAccessVersion }));
    await db.session.create({ data: { userId: platformStaff.id, token: 'h'.repeat(64), expiresAt: new Date(Date.now() + 3600_000) } });
    assert.equal((await service.revokePlatformAccess(platformAdmin.id, platformStaff.id, replaced.version)).status, 'revoked');
    assert.deepEqual(await service.platformRoles(platformStaff.id), []);
    assert.equal(await db.session.count({ where: { userId: platformStaff.id } }), 0);
    await assert.rejects(() => service.revokePlatformAccess(platformAdmin.id, platformAdmin.id, 1));
    assert.ok(staffInvitation.id);
    assert.equal((await db.party.findUnique({ where: { userId: ownerA.id } }))?.userId, ownerA.id);
    assert.equal((await service.profile(ownerA.id)).capabilities.length, 0);
    const profile = await service.updateProfile(ownerA.id, { displayName: 'Test Owner', city: 'Nablus', locale: 'ar', capabilities: ['Donor', 'Investor', 'JobSeeker'], version: 1 });
    assert.equal(profile.capabilities.length, 3);
    await assert.rejects(() => service.updateProfile(ownerA.id, { displayName: 'Old version', city: '', locale: 'ar', capabilities: [], version: 1 }));

    const input = { legalName: 'Test institution', displayName: 'Test institution', city: 'Nablus', country: 'PS', type: 'NGO' as const };
    await assert.rejects(() => service.createOrganization(unverified.id, input));
    const a = await service.createOrganization(ownerA.id, input); organizations.push(a.id);
    const b = await service.createOrganization(ownerB.id, input); organizations.push(b.id);
    assert.equal(a.verification, 'not_started');
    assert.equal((await service.contexts(ownerA.id)).length, 1);
    assert.equal((await service.contexts(ownerA.id))[0]?.permissions.includes('payout.request'), false);
    await db.organization.update({ where: { id: a.id }, data: { verification: 'verified' } });
    const updateInput = { slug: a.slug, publicDescription: 'A public description', sectors: ['Agriculture', 'Employment'], contactEmail: ownerA.email, websiteUrl: 'https://example.test', contactAddress: 'Ramallah', country: 'PS', city: 'Ramallah' };
    await assert.rejects(() => service.updateOrganization(ownerB.id, a.id, { ...updateInput, displayName: 'Other tenant', legalName: a.legalName, version: a.version }));
    const updatedOrganization = await service.updateOrganization(ownerA.id, a.id, { ...updateInput, displayName: 'Public institution', legalName: 'Changed legal institution', version: a.version });
    assert.equal(updatedOrganization.verification, 'changes_requested');
    assert.equal(updatedOrganization.version, a.version + 1);
    await assert.rejects(() => service.updateOrganization(ownerA.id, a.id, { ...updateInput, displayName: 'Stale', legalName: 'Stale', version: a.version }));
    await assert.rejects(() => service.updateOrganization(ownerB.id, b.id, { ...updateInput, displayName: b.displayName, legalName: b.legalName, version: b.version }));
    const preview = await service.publicPreview(ownerA.id, a.id);
    assert.equal(preview.displayName, 'Public institution');
    assert.deepEqual(preview.sectors, ['Agriculture', 'Employment']);
    assert.equal(Object.hasOwn(preview, 'legalName'), false);
    await assert.rejects(() => service.publicPreview(ownerB.id, a.id));
    await assert.rejects(() => service.organization(ownerA.id, b.id));
    await assert.rejects(() => service.members(ownerA.id, b.id));
    await assert.rejects(() => service.invite(ownerA.id, b.id, invited.email, ['Owner']));
    await assert.rejects(() => service.invite(ownerA.id, a.id, invited.email, ['FinanceMaker']));

    const emptyVerification = await service.verificationCase(ownerA.id, a.id);
    assert.equal(emptyVerification.version, 0);
    await assert.rejects(() => service.verificationCase(ownerB.id, a.id));
    await assert.rejects(() => service.saveVerificationCase(ownerB.id, a.id, { registrationNumber: 'REG-1', issuingAuthority: 'Registry', registeredAddress: 'Ramallah', documentExpiresAt: null, version: 0 }));
    const verificationDraft = await service.saveVerificationCase(ownerA.id, a.id, { registrationNumber: 'REG-1', issuingAuthority: 'Registry', registeredAddress: 'Ramallah', documentExpiresAt: new Date(Date.now() + 86_400_000), version: 0 });
    await assert.rejects(() => service.saveVerificationCase(ownerA.id, a.id, { registrationNumber: 'STALE', issuingAuthority: 'Registry', registeredAddress: 'Ramallah', documentExpiresAt: null, version: 0 }));
    await assert.rejects(() => service.submitVerificationCase(ownerA.id, a.id, verificationDraft.version));
    const uploadIntent = await service.createVerificationUploadIntent(ownerA.id, a.id, { fileName: 'registration.pdf', contentType: 'application/pdf', size: 8, version: verificationDraft.version });
    await assert.rejects(() => service.verificationUploadTarget(ownerB.id, a.id, uploadIntent.id, uploadIntent.token));
    await assert.rejects(() => service.verificationUploadTarget(ownerA.id, a.id, uploadIntent.id, 'x'.repeat(43)));
    assert.equal((await service.verificationUploadTarget(ownerA.id, a.id, uploadIntent.id, uploadIntent.token)).expectedSize, 8);
    await service.recordVerificationUpload(ownerA.id, a.id, uploadIntent.id, uploadIntent.token, 8);
    await assert.rejects(() => service.verificationUploadTarget(ownerA.id, a.id, uploadIntent.id, uploadIntent.token));
    assert.equal((await service.verificationUploadTarget(ownerA.id, a.id, uploadIntent.id, uploadIntent.token, 'finalize')).expectedSize, 8);
    await assert.rejects(() => service.submitVerificationCase(ownerA.id, a.id, verificationDraft.version));
    // Storage scanning is tested separately; this fixture exercises the trusted scanner-result contract.
    await service.finalizeVerificationDocument(ownerA.id, a.id, uploadIntent.id, uploadIntent.token, { clean: true, checksum: 'a'.repeat(64), actualSize: 8 });
    await assert.rejects(() => service.finalizeVerificationDocument(ownerA.id, a.id, uploadIntent.id, uploadIntent.token, { clean: true, checksum: 'a'.repeat(64), actualSize: 8 }));
    const readyVerification = await service.verificationCase(ownerA.id, a.id);
    const submissions = await Promise.allSettled([service.submitVerificationCase(ownerA.id, a.id, readyVerification.version), service.submitVerificationCase(ownerA.id, a.id, readyVerification.version)]);
    assert.equal(submissions.filter(result => result.status === 'fulfilled').length, 1);
    assert.equal((await db.organization.findUniqueOrThrow({ where: { id: a.id } })).verification, 'submitted');
    const submission = await db.organizationVerificationSubmission.findFirstOrThrow({ where: { caseId: verificationDraft.id } });
    assert.equal(submission.sequence, 1);
    assert.deepEqual((submission.snapshot as { documentIds: string[] }).documentIds, [uploadIntent.id]);
    await assert.rejects(() => db.organizationVerificationSubmission.update({ where: { id: submission.id }, data: { sequence: 2 } }));
    await assert.rejects(() => db.organizationVerificationSubmission.delete({ where: { id: submission.id } }));
    await assert.rejects(() => service.verificationReviewQueue(reviewer.id));
    await db.platformGrant.create({ data: { userId: reviewer.id, role: 'VerificationReviewer', grantedBy: reviewer.id } });
    assert.equal((await service.platformRoles(reviewer.id)).includes('VerificationReviewer'), true);
    assert.equal((await service.verificationReviewQueue(reviewer.id)).some(item => item.id === submission.id), true);
    await assert.rejects(() => service.claimVerificationReview(ownerB.id, submission.id));
    const claimed = await service.claimVerificationReview(reviewer.id, submission.id);
    assert.equal(claimed.state, 'in_review');
    assert.equal((await service.verificationReview(reviewer.id, submission.id)).case.assignedReviewerId, reviewer.id);
    const challenge = await service.createMfaChallenge(reviewer.id, reviewerSession.id, submission.id, claimed.version);
    await assert.rejects(() => service.decideVerificationReview(reviewer.id, reviewerSession.id, submission.id, { outcome: 'changes_requested', publicReason: 'يرجى إرفاق نسخة أحدث من التسجيل.', version: claimed.version, mfaChallengeId: challenge.id }));
    await service.verifyMfaChallenge(reviewer.id, reviewerSession.id, challenge.id);
    const decisions = await Promise.allSettled([
      service.decideVerificationReview(reviewer.id, reviewerSession.id, submission.id, { outcome: 'changes_requested', publicReason: 'يرجى إرفاق نسخة أحدث من التسجيل.', version: claimed.version, mfaChallengeId: challenge.id }),
      service.decideVerificationReview(reviewer.id, reviewerSession.id, submission.id, { outcome: 'changes_requested', publicReason: 'يرجى إرفاق نسخة أحدث من التسجيل.', version: claimed.version, mfaChallengeId: challenge.id })
    ]);
    assert.equal(decisions.filter(result => result.status === 'fulfilled').length, 1);
    const decision = await db.organizationVerificationDecision.findUniqueOrThrow({ where: { submissionId: submission.id } });
    assert.equal((await db.organization.findUniqueOrThrow({ where: { id: a.id } })).verification, 'changes_requested');
    assert.equal((await db.mfaChallenge.findUniqueOrThrow({ where: { id: challenge.id } })).state, 'consumed');
    const publicDecisions = await service.verificationDecisions(ownerA.id, a.id);
    assert.equal(publicDecisions[0]?.publicReason, decision.publicReason);
    assert.equal(Object.hasOwn(publicDecisions[0] ?? {}, 'reviewerId'), false);
    await assert.rejects(() => service.verificationDecisions(ownerB.id, a.id));
    await assert.rejects(() => db.organizationVerificationDecision.update({ where: { id: decision.id }, data: { publicReason: 'mutated' } }));
    await assert.rejects(() => db.organizationVerificationDecision.delete({ where: { id: decision.id } }));
    const requestedChanges = await service.verificationCase(ownerA.id, a.id);
    assert.equal(requestedChanges.state, 'changes_requested');
    const revisedDraft = await service.saveVerificationCase(ownerA.id, a.id, { registrationNumber: 'REG-2', issuingAuthority: 'Registry', registeredAddress: 'Ramallah', documentExpiresAt: new Date(Date.now() + 172_800_000), version: requestedChanges.version });
    const resubmission = await service.submitVerificationCase(ownerA.id, a.id, revisedDraft.version);
    assert.equal(resubmission.sequence, 2);
    assert.equal((await db.organizationVerificationSubmission.findUniqueOrThrow({ where: { id: resubmission.id } })).previousSubmissionId, submission.id);

    const invitation = await service.invite(ownerA.id, a.id, invited.email.toUpperCase(), ['Viewer'], config.appBaseUrl);
    assert.equal(await db.localAuthMail.count({ where: { recipient: invited.email, purpose: 'invitation' } }), 1);
    const saved = await db.invitation.findUniqueOrThrow({ where: { id: invitation.id } });
    assert.notEqual(saved.tokenHash, invitation.token);
    assert.equal(saved.tokenHash.length, 64);
    const invitationView = await service.invitationPreview(invited.id, invitation.token);
    assert.equal(invitationView.status, 'pending');
    assert.equal(invitationView.organization.displayName, updatedOrganization.displayName);
    assert.equal(invitationView.inviter.name, ownerA.name);
    assert.deepEqual(invitationView.roles, ['Viewer']);
    assert.deepEqual(Object.keys(invitationView).sort(), ['expiresAt', 'inviter', 'organization', 'roles', 'status']);
    assert.equal(Object.hasOwn(invitationView.organization, 'legalName'), false);
    assert.equal(Object.hasOwn(invitationView, 'email'), false);
    await assert.rejects(() => service.invitationPreview(ownerB.id, invitation.token));
    await assert.rejects(() => service.acceptInvitation(ownerB.id, invitation.token));
    const acceptances = await Promise.allSettled([service.acceptInvitation(invited.id, invitation.token), service.acceptInvitation(invited.id, invitation.token)]);
    assert.equal(acceptances.filter(r => r.status === 'fulfilled').length, 1);
    assert.equal(await db.membership.count({ where: { userId: invited.id, organizationId: a.id } }), 1);
    assert.equal((await service.organization(invited.id, a.id)).id, a.id);
    await assert.rejects(() => service.members(invited.id, a.id));
    await assert.rejects(() => service.organization(invited.id, b.id));
    const member = await db.membership.findUniqueOrThrow({ where: { userId_organizationId: { userId: invited.id, organizationId: a.id } } });
    await db.session.create({ data: { userId: invited.id, token: 'b'.repeat(64), expiresAt: new Date(Date.now() + 3600_000) } });
    await service.changeMembership(ownerA.id, a.id, invited.id, { version: member.version, roles: ['Viewer'], status: 'suspended' });
    assert.equal(await db.session.count({ where: { userId: invited.id } }), 0);
    await assert.rejects(() => service.organization(invited.id, a.id));
    assert.equal((await service.contexts(invited.id)).length, 0);
    await assert.rejects(() => service.invite(ownerA.id, a.id, invited.email, ['Viewer']));
    const revocable = await service.invite(ownerA.id, a.id, revokedInvitee.email, ['Viewer']);
    assert.equal((await service.invitations(ownerA.id, a.id)).some(item => item.id === revocable.id), true);
    await assert.rejects(() => service.revokeInvitation(ownerB.id, a.id, revocable.id));
    assert.equal((await service.revokeInvitation(ownerA.id, a.id, revocable.id)).status, 'revoked');
    await assert.rejects(() => service.acceptInvitation(revokedInvitee.id, revocable.token));
    await assert.rejects(() => db.invitation.update({ where: { id: revocable.id }, data: { declinedAt: new Date(), declinedBy: revokedInvitee.id } }));
    const declinable = await service.invite(ownerA.id, a.id, declinedInvitee.email, ['Viewer']);
    assert.equal((await service.declineInvitation(declinedInvitee.id, declinable.token)).status, 'declined');
    assert.equal((await service.invitationPreview(declinedInvitee.id, declinable.token)).status, 'declined');
    assert.equal(await db.membership.count({ where: { userId: declinedInvitee.id, organizationId: a.id } }), 0);
    await assert.rejects(() => service.acceptInvitation(declinedInvitee.id, declinable.token));
    await assert.rejects(() => service.declineInvitation(declinedInvitee.id, declinable.token));
    const raced = await service.invite(ownerA.id, a.id, raceInvitee.email, ['Viewer']);
    const terminalRace = await Promise.allSettled([service.acceptInvitation(raceInvitee.id, raced.token), service.declineInvitation(raceInvitee.id, raced.token)]);
    assert.equal(terminalRace.filter(result => result.status === 'fulfilled').length, 1);
    const racedRecord = await db.invitation.findUniqueOrThrow({ where: { id: raced.id } });
    assert.equal([racedRecord.consumedAt, racedRecord.revokedAt, racedRecord.declinedAt].filter(Boolean).length, 1);
    assert.equal(await db.membership.count({ where: { userId: raceInvitee.id, organizationId: a.id } }), racedRecord.consumedAt ? 1 : 0);
    await assert.rejects(() => service.changeMembership(ownerA.id, a.id, ownerA.id, { version: 1, roles: ['Viewer'], status: 'suspended' }));
    await assert.rejects(() => db.membership.updateMany({ where: { organizationId: a.id, userId: ownerA.id }, data: { status: 'suspended' } }));
    await assert.rejects(() => db.party.create({ data: { userId: invited.id, organizationId: b.id } }));
    await assert.rejects(() => db.party.create({ data: {} }));
    await assert.rejects(() => db.user.create({ data: { email: `${prefix}@EXAMPLE.TEST`, name: 'Not normalized', termsVersion: CURRENT_TERMS_VERSION, termsAcceptedAt: new Date() } }));
    assert.ok(await db.identityAuditEvent.count({ where: { organizationId: a.id } }) >= 4);
    await assert.rejects(() => db.identityAuditEvent.deleteMany({ where: { organizationId: a.id } }));
    await db.user.updateMany({ where: { id: { in: [ownerA.id, newOwner.id] } }, data: { twoFactorEnabled: true } });
    await db.membership.create({ data: { userId: newOwner.id, organizationId: a.id, roles: ['Viewer'] } });
    const transferOwnerSession = await db.session.create({ data: { userId: ownerA.id, token: 'i'.repeat(64), expiresAt: new Date(Date.now() + 3600_000) } });
    await db.session.create({ data: { userId: newOwner.id, token: 'j'.repeat(64), expiresAt: new Date(Date.now() + 3600_000) } });
    const transferVersion = (await db.organization.findUniqueOrThrow({ where: { id: a.id } })).version;
    const transferChallenge = await service.createOwnershipTransferChallenge(ownerA.id, transferOwnerSession.id, a.id, transferVersion);
    await assert.rejects(() => service.createOwnershipTransfer(ownerA.id, transferOwnerSession.id, a.id, { targetUserId: newOwner.id, version: transferVersion, mfaChallengeId: transferChallenge.id }, config.appBaseUrl));
    await service.verifyMfaChallenge(ownerA.id, transferOwnerSession.id, transferChallenge.id);
    const ownershipRequest = await service.createOwnershipTransfer(ownerA.id, transferOwnerSession.id, a.id, { targetUserId: newOwner.id, version: transferVersion, mfaChallengeId: transferChallenge.id }, config.appBaseUrl);
    assert.equal(ownershipRequest.status, 'pending');
    const ownershipMail = await db.localAuthMail.findFirstOrThrow({ where: { recipient: newOwner.email, purpose: 'ownership-transfer' }, orderBy: { createdAt: 'desc' } });
    const ownershipToken = ownershipMail.url.split('/').at(-1) ?? '';
    assert.equal((await service.ownershipTransferPreview(newOwner.id, ownershipToken)).organization.id, a.id);
    await assert.rejects(() => service.ownershipTransferPreview(ownerB.id, ownershipToken));
    const ownershipAcceptances = await Promise.allSettled([service.acceptOwnershipTransfer(newOwner.id, ownershipToken), service.acceptOwnershipTransfer(newOwner.id, ownershipToken)]);
    assert.equal(ownershipAcceptances.filter(result => result.status === 'fulfilled').length, 1);
    const formerOwnerMembership = await db.membership.findUniqueOrThrow({ where: { userId_organizationId: { userId: ownerA.id, organizationId: a.id } } });
    const newOwnerMembership = await db.membership.findUniqueOrThrow({ where: { userId_organizationId: { userId: newOwner.id, organizationId: a.id } } });
    assert.equal(formerOwnerMembership.roles.includes('Owner'), false);
    assert.equal(formerOwnerMembership.roles.includes('OrgAdmin'), true);
    assert.equal(newOwnerMembership.roles.includes('Owner'), true);
    assert.equal(await db.session.count({ where: { userId: { in: [ownerA.id, newOwner.id] } } }), 0);
    assert.equal((await db.organizationOwnershipTransfer.findUniqueOrThrow({ where: { id: ownershipRequest.id } })).state, 'accepted');
  } finally {
    // Delete only fixtures created by this invocation; preserve append-only audit records.
    await db.$transaction(async tx => {
      await tx.organization.updateMany({ where: { id: { in: organizations } }, data: { status: 'closed' } });
      // Immutable evidence is disabled only inside this rollback-safe fixture cleanup transaction.
      await tx.$executeRawUnsafe('ALTER TABLE organization_verification_decisions DISABLE TRIGGER USER');
      await tx.$executeRawUnsafe('ALTER TABLE organization_verification_submissions DISABLE TRIGGER USER');
      const cases = await tx.organizationVerificationCase.findMany({ where: { organizationId: { in: organizations } }, select: { id: true } });
      const caseIds = cases.map(item => item.id);
      await tx.organizationVerificationDecision.deleteMany({ where: { submission: { caseId: { in: caseIds } } } });
      await tx.organizationVerificationSubmission.deleteMany({ where: { caseId: { in: caseIds } } });
      await tx.organizationVerificationDocument.deleteMany({ where: { caseId: { in: caseIds } } });
      await tx.organizationVerificationCase.deleteMany({ where: { id: { in: caseIds } } });
      await tx.$executeRawUnsafe('ALTER TABLE organization_verification_submissions ENABLE TRIGGER USER');
      await tx.$executeRawUnsafe('ALTER TABLE organization_verification_decisions ENABLE TRIGGER USER');
      await tx.organizationOwnershipTransfer.deleteMany({ where: { organizationId: { in: organizations } } });
      await tx.invitation.deleteMany({ where: { organizationId: { in: organizations } } });
      await tx.membership.deleteMany({ where: { organizationId: { in: organizations } } });
      await tx.party.deleteMany({ where: { OR: [{ userId: { in: users } }, { organizationId: { in: organizations } }] } });
      await tx.organization.deleteMany({ where: { id: { in: organizations } } });
      await tx.individualProfile.deleteMany({ where: { userId: { in: users } } });
      await tx.mfaChallenge.deleteMany({ where: { userId: { in: users } } });
      await tx.session.deleteMany({ where: { userId: { in: users } } });
      await tx.platformAccessInvitation.deleteMany({ where: { createdBy: { in: users } } });
      await tx.platformGrant.deleteMany({ where: { OR: [{ userId: { in: users } }, { grantedBy: { in: users } }] } });
      await tx.twoFactor.deleteMany({ where: { userId: { in: users } } });
      await tx.localAuthMail.deleteMany({ where: { recipient: { startsWith: prefix } } });
      await tx.user.deleteMany({ where: { id: { in: users } } });
    });
    await db.$disconnect();
  }
});
