$ErrorActionPreference = 'Stop'
$basePath = $PSScriptRoot
$screenPath = Join-Path $basePath 'screens'
$partPath = Join-Path $basePath 'parts'
New-Item -ItemType Directory -Force -Path $screenPath, $partPath | Out-Null

# كل صف صفحة؛ كل فعل له صلاحية وعقد وشرط ونتيجة خاصة.
$catalog = @'
PUB-01|الرئيسية|/|زائر أو فرد|مسارات ثلاثة، مشاريع منشورة مختارة، أثر موثق مؤرخ، تعريف المنصة|استكشف المشاريع~public~NAV /explore~مشاريع منشورة فقط → فهرس قابل للتصفية;فرص الاستثمار~public~NAV /invest~يعرض وضع التجربة إن لم يفعل الاستثمار;التدريب والعمل~public~NAV /opportunities~فصل البرامج عن الوظائف;ابدأ كجهة~self~NAV /app/organizations/new~بعد الدخول → إنشاء جهة مرتبطة بالفرد
PUB-02|استكشاف المشاريع|/explore|عام|بطاقات نوع/جهة/مدينة/هدف/مقبوض/أثر وحالة|عرض المشروع~public~NAV /projects/:slug~منشور → تفاصيل؛ المحذوف 404;عرض على الخريطة~public~NAV /map?filters~يحفظ نفس المرشحات;حفظ~self~POST /bookmarks~مشروع مرئي → محفوظ دون تكرار;إزالة حفظ~self~DELETE /bookmarks/:id~صاحب العلامة فقط → تحديث القائمة
PUB-03|الخريطة|/map|عام|نقاط مشاريع عامة وتجميع وlist بديل وعدد نتائج|فتح نقطة~public~LOCAL marker panel~إحداثيات عامة → بطاقة ملخص;افتح المشروع~public~NAV /projects/:slug~لا روابط لحالات خاصة;ابحث في هذا النطاق~public~GET /map/projects?bbox~نطاق محدود → نتائج وlist محدث;استخدم موقعي~public~LOCAL browser geolocation~طلب إذن الجهاز عند الضغط فقط؛ الرفض يتيح مدينة يدويًا
PUB-04|دليل الجهات|/organizations|عام|نوع جهة، مدينة، اختصاص، توثيق بتاريخ|تفاصيل الجهة~public~NAV /organizations/:slug~جهة عامة → ملف;تصفية موثقة~public~GET /organizations?verified=true~لا اعتبار منتهية التوثيق موثقة;مسح التصفية~public~LOCAL reset filters~إعادة كل الجهات العامة
PUB-05|ملف الجهة العام|/organizations/:slug|عام|تعريف، مسؤول اتصال عمل، حالة تحقق، مشاريع، أثر، تقارير منقحة|شاهد المشاريع~public~NAV /explore?organization=:id~نطاق جهة واضح;متابعة الجهة~self~POST /follows~متابعة واحدة قابلة للإلغاء;تنزيل تقرير~public~GET /public-reports/:id/download~نسخة عامة منقحة فقط;طلب شراكة~organization.manage~NAV /org/:myOrg/agreements/new?partner=:id~عضو مخول → نموذج خاص;الإبلاغ~self~POST /tickets~سبب مطلوب → رقم تذكرة خاصة
PUB-06|المشروع الخيري|/projects/:slug|عام ومتـبرع|هدف ومقبوض ومتبق ورسوم وسياسة، جهة، مسؤول، مكان، مراحل، تحديثات، مساهمون وفق خصوصيتهم|ساهم الآن~contribution.create~NAV /checkout/:campaignId~published وقابل للتمويل → checkout;تابع الأثر~self~POST /follows~اشتراك تحديثات دون مساهمة;شارك الرابط~public~LOCAL copy public URL~رابط عام canonical دون token;شاهد الأدلة~public~GET /projects/:id/reports~منقحة ومراجعة فقط;أبلغ عن المشروع~self~POST /tickets~سبب ومشروع مرتبط → review queue
PUB-07|فهرس الاستثمار|/invest|عام|شركات وعروض حالة وأداة وحدود تمويل ومخاطر مختصرة|راجع العرض~public~NAV /invest/:id~عرض عام صالح;قارن عرضين~public~LOCAL comparison up to 3~أداة وعملة ومخاطر دون توصية عائد;فعّل ملف المستثمر~self~NAV /app/investor/eligibility~اختيار قدرة ثم أهلية منفصلة
PUB-08|تفاصيل العرض|/invest/:id|عام ومستثمر|إفصاح، شركة، أداة، سعر ووحدات، استخدام المال، minimum، deadline، مخاطر|إبداء اهتمام~self~POST /offerings/:id/interests~لا حجز ولا مال → اهتمام فقط;طلب غرفة البيانات~self~POST /offerings/:id/access-requests~شروط العرض → طلب وصول قيد مراجعة;ابدأ اكتتابًا~commitment.create~NAV /invest/:id/subscribe~أهلية وopen وتفعيل البيئة → ملخص;اقرأ الإفصاح~public~GET /offerings/:id/disclosures/current~نسخة عامة محددة مؤرخة;اطرح سؤالًا~dataroom.read~POST /offerings/:id/questions~وصول العرض → سؤال خاص قابل للرد
PUB-09|فرص التدريب والعمل|/opportunities|عام|تبويبات برامج/وظائف/تطوع، مهارات ومدينة ومدة|فتح برنامج~public~NAV /programs/:id~حالة منشورة;فتح وظيفة~public~NAV /jobs/:id~وظيفة منشورة غير مضللة;فرص تطوع~public~NAV /volunteer~فلترة مستقلة;احفظ الفرصة~self~POST /bookmarks~نوع target محفوظ
PUB-10|تفاصيل البرنامج|/programs/:id|عام وباحث عمل|مشغل وراعٍ وميزانية، سعة، شروط، ساعات، بدل، وظائف متوقعة/ملزمة، timeline|تقدم للبرنامج~application.submit~NAV /app/applications/new?program=:id~recruiting وdeadline صالح → نموذج;تواصل مع المشغل~self~POST /tickets~سؤال مرتبط بالبرنامج دون نشر بيانات;اعرض المنهج~public~GET /programs/:id/curriculum~نسخة عامة;حفظ البرنامج~self~POST /bookmarks~لا ينشئ طلبًا
PUB-11|تفاصيل الوظيفة|/jobs/:id|عام وباحث عمل|جهة، مسمى، عقد، مكان، متطلبات، أجر إن معلن، deadline|تقدم للوظيفة~application.submit~NAV /app/applications/new?job=:id~وظيفة open → نموذج خاص;شارك الوظيفة~public~LOCAL copy URL~دون بيانات مرشح;الإبلاغ عن فرصة~self~POST /tickets~بلاغ خاص مرتبط بالجهة
PUB-12|الأثر والشفافية|/impact|عام|مجاميع موثقة وتعريفاتها، unknown، تقارير وفترات|تغيير الفترة~public~GET /impact?period~فترة معتمدة → أرقام بتعريف ثابت;افتح التقرير~public~NAV /impact/reports/:id~snapshot منشور;تنزيل نسخة عامة~public~GET /public-reports/:id/download~لا بيانات أفراد
PUB-13|عن تمكين والسياسات|/about و/policies/:slug|عام|قصة المنتج، طرق التمويل، حدود التحقق، سياسة خصوصية ورسوم وشروط بنسخ|تواصل معنا~public~NAV /contact~نموذج محدد الموضوع;اقرأ نسخة سابقة~public~GET /policies/:slug/versions/:version~وثيقة منشورة ثابتة;اختر المسار~public~NAV /explore~لا وعود بنتائج أو عوائد
AUTH-01|تسجيل الدخول|/login|زائر|بريد وطريقة مصادقة، رابط استرداد، returnTo آمن|دخول~public~POST /auth/login~بيانات صحيحة → session؛ خطأ عام لا يكشف وجود بريد;نسيت كلمة المرور~public~NAV /recover~نموذج استرداد;أنشئ حسابًا~public~NAV /register~يحفظ returnTo الداخلي
AUTH-02|إنشاء الحساب|/register|زائر|اسم وبريد وcredential وشروط نسخة|إنشاء~public~POST /auth/register~تحقق المدخلات → تحقق بريد;دخول لحساب موجود~public~NAV /login~دون فقد returnTo;عرض الشروط~public~NAV /policies/terms~نسخة الموافقة معروفة
AUTH-03|التحقق والاسترداد|/verify و/recover و/reset|صاحب رمز|حالة رمز ومدة وبريد مخفف وحقل كلمة جديدة عند reset|إرسال رابط~public~POST /auth/recovery~rate limited ورسالة لا تكشف الحساب;إعادة تحقق البريد~self~POST /auth/verification-resend~مهلة بين الطلبات;تأكيد البريد~token owner~POST /auth/verify~token أحادي وصالح → verified;حفظ كلمة جديدة~token owner~POST /auth/reset~token صالح → إلغاء الجلسات وفق السياسة
AUTH-04|تهيئة الفرد|/onboarding|self|قدرات متعددة ومدينة ولغة وتفضيلات|حفظ وابدأ~profile.manage~PATCH /me/profile~ملف صالح → /app;تفعيل القدرات~profile.manage~POST /me/capabilities~لا أهلية مالية ضمنية;تخطي الاختياري~self~NAV /app~لا تجاوز تحقق مطلوب للعمليات
PER-01|الرئيسية الشخصية|/app|الفرد|ما التالي، ملخص مساهمات واستثمارات وطلبات، مواعيد|مساهماتي~self~NAV /app/contributions~قراءة مال الفرد;استثماراتي~self~NAV /app/investments~تفعيل قدرة أو عرض موجود;طلباتي~self~NAV /app/applications~كل target بعلامة نوعه;تبديل مساحة العمل~self~POST /me/context~عضوية صحيحة فقط
PER-02|المساهمات|/app/contributions|Donor|جدول مبلغ وعملة ومشروع ودفع وتسوية واسترداد|تفاصيل مساهمة~self~NAV /app/contributions/:id~صاحبها فقط;تنزيل كشف~self~POST /me/contribution-exports~نطاق الفرد وفترة → job;ساهم مجددًا~contribution.create~NAV /checkout/:campaignId~حملة تقبل التمويل؛ لا إعادة نفس charge
PER-03|تفاصيل المساهمة|/app/contributions/:id|صاحب المساهمة|مرجع، مبلغ، رسوم، حالات، خصوصية، إيصال، timeline، أثر مرتبط|تنزيل الإيصال~self~GET /contributions/:id/receipt~دفع مؤكد → إيصال لا شهادة ضريبية افتراضية;تعديل الظهور~self~PATCH /me/contributions/:id/privacy~owner → تحديث projection عامة;طلب استرداد~refund.request~POST /contributions/:id/refund-requests~مبلغ أهل للرد وسبب → requested;مشكلة في الدفع~self~POST /tickets~ربط المرجع دون بيانات بطاقة;تابع المشروع~self~NAV /projects/:slug~صفحة عامة أو سجل متاح
PER-04|Checkout خيري|/checkout/:campaignId|Donor أو ممول مؤسسي مخول|المشروع والجهة والسياق والمبلغ ورسوم وخصوصية وسياسة|متابعة للدفع~contribution.create~POST /contributions~ملخص مقبول وسعة صالحة → provider redirect;تعديل المبلغ~self~LOCAL recalculate quote~الخادم يؤكد السعر عند الإرسال;رجوع للمشروع~public~NAV /projects/:slug~دون إنشاء مساهمة ناجحة
PER-05|نتيجة الدفع|/payments/:intentId|صاحب العملية|pending/succeeded/failed/expired ومبلغ ومرجع|تحقق من الحالة~self~GET /payment-intents/:id/status~قراءة مصدر الخادم لا query success;عرض الإيصال~self~NAV /app/contributions/:id~بعد succeeded فقط;أعد المحاولة~contribution.create~POST /payment-intents/:id/retry~failed مؤكد فقط → attempt جديد مرتبط دون تكرار successful;طلب مساعدة~self~POST /tickets~unknown أو تأخر → متابعة
PER-06|محفظة الاستثمار|/app/investments|Investor|ملتزم، مسوى، مخصص، وحدات، تكلفة أصل، توزيعات|فتح الاستثمار~self~NAV /app/investments/:id~صاحب party والسياق;تنزيل بيان~self~POST /me/investment-exports~تمييز simulated ومبالغ لا قيم سوقية;استكشف عروضًا~public~NAV /invest~لا توصية عائد
PER-07|الأهلية الاستثمارية|/app/investor/eligibility|Investor|بيانات أهلية خاصة، متطلبات العرض، حالة وانتهاء|حفظ مسودة~profile.manage~PATCH /me/investor-eligibility~لا إرسال مراجعة;إرسال للمراجعة~self~POST /me/investor-eligibility/submissions~مستندات نظيفة → pending;استكمال نواقص~self~POST /me/investor-eligibility/submissions~changes_requested → نسخة جديدة
PER-08|الاكتتاب|/invest/:id/subscribe|Investor مؤهل|وحدات وسعر ومبلغ ونسخة إفصاح ومخاطر وسياق|حجز التزام~commitment.create~POST /offerings/:id/commitments~open وأهلية وسعة → expiresAt;تأكيد العقد~self~POST /commitments/:id/confirm~snapshot صحيح وإقرار → subscription;ادفع~self~POST /commitments/:id/payment-intents~تأكيد صالح وحجز لم ينته → processing;إلغاء التزام~self~POST /commitments/:id/cancel~policy تسمح → تحرير سعة دون محو تاريخ
PER-09|تفاصيل الاستثمار وغرفة البيانات|/app/investments/:id|المستثمر المخول|التزام وعقد وتخصيص وأدلة وتقارير وتوزيعات|تنزيل إثبات الحصة~self~GET /allocations/:id/proof~allocation مثبت فقط;اقبل NDA~self~POST /offerings/:id/nda-acceptances~نسخة محددة → منح حسب سياسة;افتح مستند غرفة~dataroom.read~GET /documents/:id/download~grant صالح → رابط مؤقت مدقق;اطرح سؤالًا~dataroom.read~POST /offerings/:id/questions~مرتبط بالعرض;اعترض على بيان~self~POST /tickets~مرجع استثمار → نزاع مراجعة
PER-10|ملف المهارات|/app/career/profile|JobSeeker|مهارات وتعليم وخبرة ومدينة وتوفر وسيرة وخصوصية|حفظ الملف~profile.manage~PATCH /me/candidate-profile~موافقة مشاركة مضبوطة;رفع سيرة~profile.manage~POST /documents/upload-intents~فحص قبل ربط;معاينة ما يراه صاحب العمل~self~GET /me/candidate-profile/employer-preview~allowlist؛ لا ملفات مساعدة;اكتشف فرصًا~public~NAV /opportunities~فلاتر مهارات قابلة للتعديل
PER-11|طلب جديد أو مسودة|/app/applications/new و/app/applications/:id/edit|JobSeeker|الفرصة وإجابات وسيرة وموافقات ومهلة|حفظ مسودة~application.submit~POST /applications أو PATCH /applications/:id~draft صالح جزئيًا → saved_at;إرسال الطلب~application.submit~POST /applications/:id/submit~required وdeadline وعدم duplicate → submitted;معاينة~self~LOCAL application preview~نسخة ما سيستلمه المراجع;إلغاء المسودة~self~POST /applications/:id/discard~draft فقط → archived draft
PER-12|طلباتي وتفاصيلها|/app/applications و/app/applications/:id|صاحب الطلب|timeline، جهة، موعد، قرارات معلنة، نقص وثائق|فتح الطلب~self~NAV /app/applications/:id~owner;سحب الطلب~application.submit~POST /applications/:id/withdraw~حالة قابلة للانسحاب → سبب وتحرير دعوة;تأكيد مقابلة~self~POST /interviews/:id/confirm~موعد صالح → confirmed;طلب تغيير موعد~self~POST /interviews/:id/reschedule-requests~سبب وبدائل → طلب لا تعديل صامت;قبول المقعد~self~POST /enrollments/:id/accept~دعوة صالحة وسعة → confirmed
PER-13|تدريبي|/app/training/:enrollmentId|متدرب|جدول وحضور وتقييم وبدلات ومتطلبات شهادة|افتح الجلسة~self~NAV /app/training/:id/sessions/:sid~مسجل بهذه الجلسة;اعترض على حضور~self~POST /attendance/:id/objections~سبب → مراجعة؛ لا تعديل مباشر;تنزيل الشهادة~self~GET /certificates/:id/download~صالحة واستحقاق مثبت;اعرض البدلات~self~GET /me/stipends?enrollment=:id~مستحق/محجوز/مدفوع منفصلة;طلب انسحاب~self~POST /enrollments/:id/withdrawal-requests~سياسة البرنامج → تقييم مستحقات
PER-14|العرض الوظيفي والمتابعة|/app/job-offers/:id و/app/placements/:id|المرشح|نسخة شروط ومدة، تاريخ بدء، نتيجة متابعة|اقبل العرض~self~POST /job-offers/:id/accept~نسخة حالية ومهلة → accepted لا employed;ارفض العرض~self~POST /job-offers/:id/decline~قرار محفوظ;أكد بدء العمل~self~POST /placements/:id/start-confirmations~تاريخ فعلي ودليل عند اللزوم → بانتظار تحقق;أجب عن المتابعة~self~POST /placements/:id/followups~checkpoint مستحق → نتيجة ومصدر;اعترض على النتيجة~self~POST /tickets~placement مرتبط → disputed
PER-15|طلبات المساعدة|/app/assistance و/app/assistance/:id|Beneficiary|احتياج خاص وجهة مخولة وconsent وحالة وتسليم|طلب جديد~self~POST /assistance~أقل بيانات لازمة → draft/submitted وفق النموذج;أرسل مستندًا مطلوبًا~self~POST /assistance/:id/replies~مستند نظيف وجهة مسندة;أكد استلام دعم~self~POST /assistance/:id/deliveries/:did/confirm~تسليم محدد → تأكيد لا قبض مال جديد;اعترض~self~POST /tickets~لا يحتسب disputed كأثر نهائي;اسحب موافقة مشاركة~self~POST /assistance/:id/consent-revocations~شرح أثرها على المعالجة والسجل
PER-16|أفكاري واحتضاني|/app/proposals و/app/proposals/:id|صاحب فكرة|فكرة خاصة وحالة وmentor ومراحل واتفاق|أنشئ فكرة~self~POST /proposals~draft خاص;أرسل للحاضنة~self~POST /proposals/:id/submit~حقول وموافقة جهة → review;اقبل اتفاق احتضان~self~POST /incubation-agreements/:id/accept~نسخة وحقوق معلنة → active;قدم دليل مرحلة~self~POST /incubation-milestones/:id/evidence~مرحلة مفتوحة → مراجعة;أنشئ Startup مرتبطة~organization.manage~NAV /app/organizations/new?proposal=:id~لا أسهم تلقائية ولا نسخ هوية
PER-17|التطوع|/volunteer و/app/volunteering|Volunteer|فرص وطلبات ومهام وساعات معتمدة|تقدم~self~POST /volunteer-applications~فرصة open وعدم تكرار;اقبل مهمة~self~POST /volunteer-assignments/:id/accept~مسندة للفرد وصالحة;سجل ساعات~self~POST /volunteer-hours~مهمة نشطة → بانتظار اعتماد;اسحب طلبًا~self~POST /volunteer-applications/:id/withdraw~سياسة فرصة → withdrawn
PER-18|إعدادات الفرد والأمان|/app/settings|self|ملف وقدرات ولغة وإشعارات وجلسات وMFA|حفظ الإعدادات~profile.manage~PATCH /me/preferences~لا تعطيل رسائل تشغيل إلزامية بصمت;إلغاء جلسة~self~POST /sessions/:id/revoke~جلسة مملوكة → revoked;إعداد MFA~self~POST /me/mfa/enroll~تحقق challenge قبل enabled;طلب نسخة بيانات~self~POST /me/data-exports~إعادة تحقق → ملف خاص مؤقت;طلب إغلاق حساب~self~POST /me/closure-requests~التزامات توضح قبل الإغلاق
PER-19|الإشعارات والمحفوظات|/app/notifications و/app/saved|self|unread ومرجع آمن وموارد محفوظة|قراءة إشعار~self~POST /notifications/:id/read~owner ثم NAV مصرح;تعليم الكل مقروء~self~POST /me/notifications/read-all~حتى timestamp معلوم;إزالة حفظ~self~DELETE /bookmarks/:id~owner;إلغاء متابعة~self~DELETE /follows/:id~لا يلغي مساهمة أو طلبًا
PER-20|الدعم|/contact و/app/tickets/:id|مقدم تذكرة|موضوع ورسائل ومرفقات وحالة ومسؤول|أرسل تذكرة~self أو public rate-limited~POST /tickets~تحقق قناة الرد؛ حساسة تتطلب دخول;أضف ردًا~ticket participant~POST /tickets/:id/replies~مشارك فقط وملف نظيف;أعد فتح~ticket participant~POST /tickets/:id/reopen~سياسة تسمح وسبب جديد;أكد الحل~ticket participant~POST /tickets/:id/confirm-resolution~لا يلغي نزاعًا ماليًا تلقائيًا
ORG-01|إنشاء جهة|/app/organizations/new|فرد مسجل|نوع واسم قانوني واسم عام وبلد ومدينة ومفوض|أنشئ الجهة~self~POST /orgs~ملف صالح → membership Owner وverification not_started;حفظ بيانات أولية~self~LOCAL draft~تبقى محليًا دون ادعاء إنشاء;تابع التوثيق~organization.manage~NAV /org/:id/verification~بعد نجاح إنشاء فقط
ORG-02|لوحة الجهة|/org/:orgId|عضو نشط|مهام حسب الدور، توثيق، أرقام معرفة وروابط مصدر، مشاريع نشطة|مشروع جديد~project.create~NAV /org/:id/projects/new~capability مناسبة;راجع المهام~member active~NAV /org/:id/tasks~قائمة بحسب permissions;المالية~finance.read~NAV /org/:id/finance~صلاحية قراءة مالية صريحة;إدارة الفريق~organization.manage~NAV /org/:id/team~لا تعرض إعدادات owner لغيره
ORG-03|ملف وإعدادات الجهة|/org/:orgId/settings|Owner/Admin|اسم عام وقطاعات وشعار وعنوان اتصال وصفحة عامة|حفظ~organization.manage~PATCH /orgs/:id~تغيير قانوني يطلب إعادة تحقق;معاينة الملف العام~organization.manage~GET /orgs/:id/public-preview~نفس public projection;طلب تغيير بنك~bank.manage~POST /orgs/:id/bank-change-requests~MFA ومراجعة مستقلة → pending لا تبديل فوري;نقل الملكية~ownership.transfer~POST /orgs/:id/ownership-transfers~قبول الطرف الجديد قبل سحب القديم
ORG-04|توثيق الجهة|/org/:orgId/verification|Owner/Admin|case حالة ونسخ وملاحظات ووثائق|حفظ~organization.manage~PATCH /orgs/:id/verification~draft;إرسال~organization.manage~POST /orgs/:id/verification/submissions~وثائق سليمة → submitted;الرد على نواقص~organization.manage~POST /orgs/:id/verification/submissions~نسخة جديدة تربط السابقة;عرض قرار~organization.manage~GET /orgs/:id/verification/decisions~دون ملاحظات تشغيل محمية
ORG-05|الفريق والصلاحيات|/org/:orgId/team|Owner/Admin|أعضاء وأدوار ودعوات وحالة ونطاق|دعوة عضو~member.invite~POST /orgs/:id/invitations~أدوار لا تتجاوز المانح;تعديل الدور~member.role.update~PATCH /orgs/:id/members/:uid~لا إزالة آخر owner ولا منح محظور;إيقاف عضوية~member.role.update~POST /orgs/:id/members/:uid/suspend~إلغاء وصول وجلسات سياق;إلغاء دعوة~member.invite~POST /orgs/:id/invitations/:iid/revoke~دعوة لم تقبل → revoked
ORG-06|قائمة المشاريع|/org/:orgId/projects|PM/Viewer|نوع وحالة وتمويل وتنفيذ ومسؤول وآخر تحديث|أنشئ مشروعًا~project.create~NAV /org/:id/projects/new~نوع متاح للجهة;فتح إدارة~project.read~NAV /org/:id/projects/:pid~tenant scope;نسخ كمسودة~project.create~POST /orgs/:id/projects/:pid/duplicate~لا نسخ أموال أو متبرعين أو موافقات;أرشفة~project.archive~POST /orgs/:id/projects/:pid/archive~إغلاق وتسوية أولًا
ORG-07|محرر المشروع|/org/:orgId/projects/new و/projects/:pid/edit|ProjectManager|خطوات تعريف/مكان/مسؤول/ميزانية/مراحل/وثائق/سياسة|حفظ مسودة~project.update~POST /orgs/:id/projects أو PATCH /orgs/:id/projects/:pid~version وحالة قابلة;إضافة مرحلة~project.update~POST /orgs/:id/projects/:pid/milestones~تاريخ ووزن وميزانية منضبطة;معاينة عامة~project.read~GET /orgs/:id/projects/:pid/public-preview~لا نشر فعلي;إرسال مراجعة~project.submit~POST /orgs/:id/projects/:pid/submit~اكتمال وتوثيق → snapshot
ORG-08|إدارة المشروع والمراحل|/org/:orgId/projects/:pid|PM/Finance حسب القسم|timeline وميزانية وأدلة وطلبات صرف وتقارير|نشر تحديث~report.publish~POST /orgs/:id/projects/:pid/updates~تنقيح وموافقة صور;تقديم إثبات مرحلة~project.update~POST /orgs/:id/projects/:pid/milestones/:mid/evidence~مرحلة نشطة → in_review;إيقاف جمع~project.pause~POST /orgs/:id/projects/:pid/pause~سبب وتأثير → منع مساهمات جديدة;طلب إغلاق~project.close~POST /orgs/:id/projects/:pid/close~تقرير وتسوية → impact_review;طلب تعديل ميزانية~project.update~POST /orgs/:id/projects/:pid/budget-revisions~نسخة جديدة ومراجعة لا overwrite
ORG-09|المساهمون والمساهمات|/org/:orgId/contributions|Finance أو موظف مخول|مبالغ وحالات ومشاريع وظهور عام وبيانات اتصال محدودة|تفاصيل مالية~contribution.read~GET /orgs/:id/contributions/:cid~لا بيانات خارج الجهة;تصدير منقح~finance.export~POST /orgs/:id/contribution-exports~scope وفلاتر وبدون هوية مجهول افتراضيًا;طلب كشف هوية تشغيلي~contribution.identity.read~POST /orgs/:id/contributions/:cid/identity-access~سبب وتدقيق وحاجة → كشف مخول;طلب استرداد~refund.request~POST /contributions/:id/refund-requests~remaining وسياسة
ORG-10|المالية والدفتر|/org/:orgId/finance|Finance|pools وعملات ومقبوض ورسوم ومسوى ومحجوز ومتاح وقيود|فتح قيد~finance.read~GET /orgs/:id/ledger/:txid~قراءة append-only;تصفية وعاء~finance.read~GET /orgs/:id/finance/summary?pool=:pid~لا دمج عملات;طلب صرف~payout.request~NAV /org/:id/payouts/new~pool متاح;تنزيل كشف~finance.export~POST /orgs/:id/ledger-exports~snapshot مؤرخ؛ لا تعديل رصيد
ORG-11|إنشاء صرف|/org/:orgId/payouts/new|FinanceMaker|وعاء وبند ومرحلة ومستفيد ومبلغ وفاتورة وملخص|راجع الطلب~payout.request~LOCAL review summary~تحقق واجهة ثم خادم عند الإرسال;أرسل للاعتماد~payout.request~POST /orgs/:id/payouts~رصيد ومستفيد وversion → حجز requested;إلغاء قبل إرسال~payout.request~LOCAL discard draft~لا حجز إن لم ينشأ الطلب
ORG-12|مراجعة وتتبع الصرف|/org/:orgId/payouts/:id|Maker/Approver/Finance|طلب ثابت وmaker وأدلة وحجز وموافقات وحالة مزود|اعتماد~payout.approve~POST /payouts/:id/approve~actor مختلف وMFA وsnapshot → approved;رفض~payout.approve~POST /payouts/:id/reject~سبب → تحرير الحجز وفق الحالة;سحب طلب~payout.request~POST /payouts/:id/withdraw~قبل التنفيذ وبشروط → cancelled;تحديث حالة~finance.read~GET /payouts/:id~unknown لا retry مالي;عرض إثبات~finance.read~GET /payouts/:id/proof~paid مثبت فقط
ORG-13|التقارير|/org/:orgId/reports و/reports/:rid|PM/Analyst|تقارير مسودة ومراجعة ومنشورة وأثر ومصروفات مصدرية|أنشئ تقريرًا~report.create~POST /orgs/:id/reports~فترة ومشروع → draft;اجلب مؤشرات~report.create~GET /orgs/:id/reports/metrics~تعريفات ثابتة لا أرقام مخترعة;أرسل للمراجعة~report.submit~POST /orgs/:id/reports/:rid/submit~أدلة وتنقيح → review;تنزيل نسخة~report.read~GET /documents/:id/download~classification مناسب;نشر المعتمد~report.publish~POST /orgs/:id/reports/:rid/publish~مراجعة مكتملة → snapshot عام
BUS-01|عروض الشركة|/org/:orgId/offerings|InvestmentManager|عروض وسعة وتعهدات ومدفوع ومسوى ومخصص وتقارير|عرض جديد~offering.manage~NAV /org/:id/offerings/new~issuer capability وتوثيق;إدارة العرض~offering.manage~NAV /org/:id/offerings/:oid~tenant;إغلاق للاكتتاب~offering.manage~POST /orgs/:id/offerings/:oid/close~open وشروط إغلاق → closing لا allocated
BUS-02|محرر العرض|/org/:orgId/offerings/new و/:oid/edit|InvestmentManager|أداة وأسهم حالية ومعروضة وسعر وهدف واستخدام وإفصاح|حفظ~offering.manage~POST /orgs/:id/offerings أو PATCH /orgs/:id/offerings/:oid~draft/version؛ لا تعديل جوهري صامت;فحص الحسابات~offering.manage~POST /orgs/:id/offerings/:oid/validate~سعر ووحدات ونسبة متسقة;إرسال عناية~offering.manage~POST /orgs/:id/offerings/:oid/submit~إفصاح كامل → review;إنشاء تعديل إفصاح~offering.manage~POST /orgs/:id/offerings/:oid/disclosure-revisions~وقف/معالجة موافقات حسب سياسة
BUS-03|غرفة البيانات والأسئلة|/org/:orgId/offerings/:oid/dataroom|InvestmentManager|مستندات وتصنيف ومنح وصول وأسئلة وسجل تنزيل|أضف مستندًا~offering.manage~POST /orgs/:id/offerings/:oid/documents~فحص وتصنيف/version;منح وصول~dataroom.manage~POST /orgs/:id/offerings/:oid/grants~مستثمر محدد وexpiry وشروط;سحب وصول~dataroom.manage~POST /dataroom-grants/:id/revoke~سجل سبب لا محو عقد قديم;رد على سؤال~offering.manage~POST /investor-questions/:id/replies~نطاق العرض ولا كشف مستثمرين آخرين
BUS-04|الاكتتابات والتخصيص|/org/:orgId/offerings/:oid/allocations|InvestmentManager/Finance|التزامات وتسوية وعقود ووحدات وبواقي وإثباتات|معاينة تخصيص~allocation.preview~POST /orgs/:id/offerings/:oid/allocations/preview~closing وبيانات مثبتة → preview فقط;أرسل تثبيت التخصيص~allocation.request~POST /orgs/:id/offerings/:oid/allocations/requests~نسخة حساب وعقود → مراجعة مخولة;تنزيل سجل~investment.export~POST /orgs/:id/offerings/:oid/allocation-exports~خاص ومؤرخ;فتح تعارض~finance.read~POST /tickets~مبلغ/عقد غير مطابق → مراجعة
BUS-05|تقارير الشركة والتوزيعات|/org/:orgId/investor-relations|InvestmentManager/Finance|مستحقات تقارير، تحديثات، توزيع مقترح ومعتمد ومدفوع|نشر تقرير معتمد~report.publish~POST /orgs/:id/company-reports~نسخة ومراجعة → إشعار المستثمرين;اقترح توزيعًا~distribution.request~POST /orgs/:id/distributions~مبلغ ومصدر وsnapshot holdings → requested;اعتماد توزيع~distribution.approve~POST /distributions/:id/approve~مستقل ورصيد وحقوق مثبتة;سجل حدث شركة~offering.manage~POST /orgs/:id/corporate-events~مستند وأثر → مراجعة لا تعديل حصص يدوي
BUS-06|الشراكات والمنح|/org/:orgId/agreements و/:aid|Owner/PM/Sponsor|طرفان، نوع نقدي/عيني، التزامات ومراحل ونسخ وتمويل|اقتراح اتفاق~agreement.manage~POST /orgs/:id/agreements~جهة شريكة ومشروع ونسخة → draft;إرسال للطرف الآخر~agreement.manage~POST /agreements/:id/submit~ممثل مخول → pending_acceptance;قبول النسخة~agreement.accept~POST /agreements/:id/accept~صلاحية الطرف الصحيح → active بعد قبول الطرفين;اعتماد تسليم~agreement.review~POST /agreements/:id/milestones/:mid/decision~دليل وقرار مسبب;افتح نزاعًا~agreement.manage~POST /tickets~ربط الاتفاق دون صرف تلقائي
PRG-01|لوحة الحاضنة والبرامج|/org/:orgId/programs|ProgramManager|دفعات ومقاعد وطلبات وميزانيات وإكمال وبدء عمل|برنامج جديد~program.manage~NAV /org/:id/programs/new~جهة مشغلة capability;فتح برنامج~program.read~NAV /org/:id/programs/:pid~tenant;طلبات بحاجة قرار~application.review~NAV /org/:id/applications?pending=true~نطاق برامج الجهة
PRG-02|محرر البرنامج|/org/:orgId/programs/new و/:pid/edit|ProgramManager|مشغل وراعٍ واتفاق وتمويل ومنهج وجدول وسعة وبدل ووظائف|حفظ~program.manage~POST /orgs/:id/programs أو PATCH /orgs/:id/programs/:pid~حقول متسقة/version;إضافة دفعة~program.manage~POST /orgs/:id/cohorts~سعة وتاريخ ضمن البرنامج;أرسل مراجعة~program.manage~POST /orgs/:id/programs/:pid/submit~تمويل ومسؤول وخطة قبول → review;افتح التقديم~program.publish~POST /orgs/:id/programs/:pid/publish~مراجعة مكتملة ونافذة صحيحة
PRG-03|فرز المتقدمين|/org/:orgId/applications|Recruiter/ProgramManager|جدول طلبات مهارات وحالة ونتيجة rubric دون بيانات مساعدة|افتح المرشح~application.review~GET /orgs/:id/applications/:aid~target داخل نطاق الجهة;قيّم~application.review~POST /orgs/:id/applications/:aid/reviews~rubric وسبب وحفظ خاص;حدد مقابلة~application.review~POST /orgs/:id/applications/:aid/interviews~موعد/منطقة زمنية → دعوة;قبول أو انتظار أو رفض~application.review~POST /orgs/:id/applications/:aid/decision~قرار محدد وسبب وسعة → invitation/waitlist/rejected;تصدير مرشحين~candidate.export~POST /orgs/:id/application-exports~حقول لازمة وموافقة مشاركة
PRG-04|إدارة الدفعة|/org/:orgId/cohorts/:cid|ProgramManager/Trainer|أعضاء مؤكدون وسعة وجدول ومدربون وحضور|إسناد مدرب~program.manage~POST /cohorts/:id/trainers~عضو نشط ونطاق محدود;إنشاء جلسة~program.manage~POST /cohorts/:id/sessions~وقت ضمن المنهج;دعوة التالي من الانتظار~application.review~POST /cohorts/:id/waitlist/invite-next~مقعد متاح وترتيب موثق;تسجيل انسحاب~program.manage~POST /enrollments/:id/withdraw~سبب ومستحقات لا حذف سجل
PRG-05|الحضور والتقييم|/org/:orgId/cohorts/:cid/sessions/:sid|Trainer المسند|قائمة متدربين وحالة حضور وعذر وتقييم|حفظ الحضور~attendance.record~PUT /cohorts/:id/sessions/:sid/attendance~نطاق جلسة وversion → سجل واحد لكل متدرب;تعديل بعد الإقفال~attendance.correct~POST /attendance/:id/revisions~سبب ومراجعة عند أثر مالي;سجل تقييمًا~assessment.record~POST /assessments/:id/results~rubric وscale؛ مؤهل للإكمال بعد تحقق;راجع اعتراضًا~attendance.review~POST /attendance-objections/:id/decision~مراجع مخول وسبب → تعديل مدقق
PRG-06|البدلات والشهادات|/org/:orgId/programs/:pid/outcomes|ProgramManager/Finance|استحقاقات حضور، بدلات محجوزة ومدفوعة، أهلية شهادة|كوّن دفعة بدلات~stipend.request~POST /stipends/batches~حضور مثبت وفترة غير مدفوعة → طلب مالي;أرسل للصرف~payout.request~POST /orgs/:id/payouts~رصيد واعتماد مستقل؛ لا دفع من زر شهادة;إصدار شهادة~certificate.issue~POST /certificates~متطلبات مكتملة → publicId محدود;سحب شهادة~certificate.revoke~POST /certificates/:id/revoke~سبب ودليل وإشعار خاص
PRG-07|إدارة الوظائف|/org/:orgId/jobs و/:jid/edit|Recruiter|وظائف وعقود ومواقع ومتطلبات وطلبات|أنشئ وظيفة~job.manage~POST /orgs/:id/jobs~draft تابع للجهة;حفظ تعديل~job.manage~PATCH /orgs/:id/jobs/:jid~version وتغيير جوهري موضح;انشر~job.publish~POST /orgs/:id/jobs/:jid/publish~حقول ومراجعة الجهة → open;أغلق~job.manage~POST /orgs/:id/jobs/:jid/close~سبب وتعامل مع طلبات قائمة;رشح متدربين~application.review~POST /orgs/:id/jobs/:jid/referrals~موافقة الشاب على مشاركة ملفه
PRG-08|عروض العمل|/org/:orgId/job-offers|Recruiter|مرشحون ومقابلات ونسخ عروض ومواعيد بدء|إنشاء عرض~job.manage~POST /orgs/:id/job-offers~مرشح ووظيفة وشروط ومهلة;إرسال العرض~job.manage~POST /job-offers/:id/send~نسخة ثابتة → إشعار المرشح;سحب عرض~job.manage~POST /job-offers/:id/withdraw~قبل قبول أو إجراء خاص عند تعاقد؛ سبب;تسجيل بدء من جهة العمل~placement.verify~POST /placements/:id/start-confirmations~تاريخ ودليل → مراجعة توافق الطرفين
PRG-09|التوظيف والمتابعة|/org/:orgId/placements|ProgramManager/Recruiter|started ومتابعات مستحقة وretained/ended/unknown/disputed|طلب متابعة~placement.verify~POST /placements/:id/followup-requests~checkpoint مستحق → إشعار دون إنشاء نجاح;تسجيل نتيجة~placement.verify~POST /placements/:id/followups~مصدر ودليل وتاريخ؛ unknown متاح;حل تعارض~placement.review~POST /placements/:id/review-decisions~طرف مخول وسبب → نتيجة موثقة;تنزيل تقرير أثر~report.read~POST /orgs/:id/placement-exports~منقح وتعريف المقام
PRG-10|أفكار الاحتضان والإرشاد|/org/:orgId/proposals و/:pid|ProgramManager/Mentor|فكرة خاصة ومراجعة واتفاق وmentor ومراحل|قبول أو رفض فكرة~proposal.review~POST /orgs/:id/proposals/:pid/decision~سبب ومعايير → قرار;تعيين مرشد~program.manage~POST /proposals/:id/mentor-assignments~وصول لفكرة مسندة فقط;اقتراح اتفاق~agreement.manage~POST /incubation-agreements~حقوق ومال وحدود واضحة;اعتماد مرحلة~proposal.review~POST /incubation-milestones/:id/decision~دليل ومراجعة → إنجاز;إغلاق احتضان~program.manage~POST /proposals/:id/close~نتيجة ومصروفات وخطة متابعة
PRG-11|محفظة الراعي|/org/:orgId/sponsorships|Sponsor/Analyst/Finance|اتفاقات تمويل ومراحل صرف وتقارير منقحة وانحرافات|تمويل اتفاق~sponsorship.fund~POST /agreements/:id/funding-intents~صلاحية مالية وسياق وعملة → intent;مراجعة تقرير~agreement.review~POST /agreements/:id/reports/:rid/decision~أثر ومال موثق → approve/changes;فتح انحراف~agreement.manage~POST /tickets~اتفاق وفترة → خطة تصحيح;تنزيل تقرير مجمع~report.read~POST /orgs/:id/sponsor-exports~لا ملفات متدربين خاصة
PRG-12|طلبات المساعدة داخل الجمعية|/org/:orgId/assistance/:caseId|مسؤول حالة مسند|ملف احتياج خاص وconsent وأدلة وخطة وتسليم|طلب توضيح~assistance.manage~POST /assistance/:id/clarifications~حالة مسندة → رسالة خاصة;قرار أهلية~assistance.manage~POST /assistance/:id/decisions~سبب ومعايير دون نشر;تسجيل تسليم~assistance.manage~POST /assistance/:id/deliveries~دليل ومصدر دعم → انتظار تأكيد;إغلاق حالة~assistance.manage~POST /assistance/:id/close~تسليم/رفض مسبب ونزاعات محسومة
PRG-13|إدارة التطوع|/org/:orgId/volunteering|VolunteerCoordinator|فرص وطلبات ومهام وساعات|نشر فرصة~volunteer.manage~POST /orgs/:id/volunteer-opportunities~مسؤول ومهام وسعة ومتطلبات;قرار طلب~volunteer.manage~POST /volunteer-applications/:id/decision~نطاق جهة وسعة;إسناد مهمة~volunteer.manage~POST /volunteer-assignments~متطوع موافق ونطاق بيانات محدود;اعتماد ساعات~volunteer.manage~POST /volunteer-hours/:id/approve~تحقق وعدم اعتماد ذاتي عند تعارض
ADM-01|قوائم عمل الإدارة|/admin|موظف منصة محدود|queues حسب permissions وأعمار ومهام مسندة|استلم مهمة~review.claim~POST /admin/tasks/:id/claim~غير مسندة أو transfer مخول;فتح المهمة~scoped review~NAV /admin/reviews/:type/:id~اختصاص مطابق;إعادة إسناد~review.assign~POST /admin/tasks/:id/assign~صلاحية مشرف وموظف مختص
ADM-02|مراجعة التوثيق|/admin/verifications/:id|VerificationReviewer|نسخ وثائق وفحص وتواريخ وملاحظات وسجل|اعتماد~verification.review~POST /admin/verifications/:id/decision~decision=verified وفحص مكتمل وعدم تعارض;طلب تعديل~verification.review~POST /admin/verifications/:id/decision~decision=changes_requested وأسباب حقول;رفض~verification.review~POST /admin/verifications/:id/decision~reason وإمكانية إعادة تقديم معلنة
ADM-03|مراجعة المشروع والبرنامج والتقرير|/admin/reviews/:type/:id|Content/ImpactReviewer|snapshot وميزانية وسياسة وأدلة وتنقيح ومعاينة عامة|اعتماد~content.review~POST /admin/reviews/:type/:id/decision~type ضمن نطاق المراجع ونسخة ثابتة;طلب تعديل~content.review~POST /admin/reviews/:type/:id/decision~حقول وأسباب → changes_requested;رفض~content.review~POST /admin/reviews/:type/:id/decision~سبب لا محو تاريخ;معاينة النشر~content.review~GET /admin/reviews/:type/:id/public-preview~نفس allowlist العامة
ADM-04|مراجعة الاستثمار والأهلية|/admin/investment-reviews/:id|RiskReviewer|عرض/أهلية وأداة وإفصاح وعقود ومخاطر وتعارضات|قرار عرض~offering.review~POST /admin/offerings/:id/decision~due_diligence والنسخة مثبتة;قرار أهلية~eligibility.review~POST /admin/eligibility/:id/decision~أسباب وتاريخ انتهاء حسب سياسة;اعتماد تخصيص~allocation.finalize~POST /admin/offerings/:id/allocations/finalize~تسوية وشروط وإثبات خارجي أو simulated واضح;طلب توضيح~offering.review~POST /admin/investment-reviews/:id/clarifications~نواقص محددة
ADM-05|مركز المدفوعات والتسوية|/admin/finance|FinanceOperator|inbox/intent/settlement/reconciliation ومبالغ وفروقات|استيراد كشف~reconciliation.manage~POST /admin/reconciliation/imports~hash ومصدر وبيئة → batch;مطابقة~reconciliation.manage~POST /admin/reconciliation/:id/run~لا تكرار قيود على إعادة run;حل فرق~reconciliation.manage~POST /admin/reconciliation/items/:id/resolutions~دليل وسبب أو قيد تصحيح معتمد;استعلم حالة مزود~payment.inquire~POST /admin/payment-intents/:id/inquire~قراءة مزود مرجعية لا charge جديد;إعادة معالجة حدث~webhook.replay~POST /admin/webhooks/:id/replay~نفس event_id وidempotency
ADM-06|تنفيذ الصرف والاسترداد|/admin/disbursements/:id|FinanceOperator/Approver|طلب وموافقة وحجز ومستفيد ومزود وunknown|نفذ صرفًا~payout.execute~POST /admin/payouts/:id/execute~موافقة حالية وعدم تجميد → processing;اعتمد استردادًا~refund.approve~POST /refunds/:id/approve~مستقل ومبلغ قابل للرد;نفذ استردادًا~refund.execute~POST /admin/refunds/:id/execute~approved ومصدر وتغطية رسوم;استعلم عملية مجهولة~payment.inquire~POST /admin/disbursements/:id/inquire~لا retry أعمى؛ إثبات paid/failed
ADM-07|التذاكر والبلاغات والتجميد|/admin/tickets/:id|Support/Risk حسب الفعل|سياق منقح وأدلة ومشاركون وقرار وسجل|رد~support.manage~POST /tickets/:id/replies~دون كشف معلومات طرف ثالث;صعّد~support.manage~POST /admin/tickets/:id/escalate~اختصاص وأولوية ومسؤول;جمد نطاقًا~risk.freeze~POST /admin/subjects/:id/freeze~سبب ونطاق collect/payout/publish واضح;فك تجميد~risk.unfreeze~POST /admin/subjects/:id/unfreeze~مراجعة وسبب؛ لا يعيد نشر تلقائي;حل التذكرة~support.manage~POST /admin/tickets/:id/resolve~resolution وحقوق مالية باقية موضحة
ADM-08|التدقيق وصلاحيات التشغيل|/admin/audit و/admin/team|Auditor/PlatformAdmin|سجل immutable وفلاتر ووصول حساس وموظفون|فتح حدث~audit.read~GET /admin/audit/:id~حقول منقحة؛ لا تعديل;تصدير تدقيق~audit.export~POST /admin/audit-exports~نطاق وسبب ورابط مؤقت;دعوة موظف~platform.access.manage~POST /admin/team/invitations~منح محدود وMFA؛ لا finance ضمني;تعديل منح مؤقتة~platform.access.manage~POST /admin/team/:id/grants~expiry وتدقيق وفصل تعارض;إلغاء وصول~platform.access.manage~POST /admin/team/:id/revoke~إلغاء الجلسات فورًا
ADM-09|مراقبة النظام والنشر المالي|/admin/operations|Ops/مفوض إطلاق|health وqueues وlags ونسخ سياسة وfeature flags وقرار إطلاق|أعد job غير مالي~ops.jobs.manage~POST /admin/jobs/:id/retry~idempotent؛ المالي عبر inquiry;اعرض سجل حادث~ops.read~GET /admin/incidents/:id~منقح ومخول;غير feature flag~platform.release.manage~POST /admin/feature-flags/:id/change-requests~قرار مدقق ومتطلبات إطلاق؛ لا تشغيل مال بضغطة دون شروط;سجل تمرين استعادة~ops.manage~POST /admin/restore-drills~أدلة فعلية وRPO/RTO مقاسان
'@

$catalog += @'

SUP-01|قبول دعوة مؤسسة|/invitations/:token|صاحب البريد المدعو|اسم جهة ودور مطلوب ومدة دعوة واسم داعٍ مسموح|قبول الدعوة~token owner~POST /invitations/:token/accept~session ببريد مطابق ودعوة صالحة → عضوية;دخول بالبريد المدعو~public~NAV /login~returnTo داخلي يحفظ غرض الدعوة;رفض الدعوة~token owner~POST /invitations/:token/decline~رمز صالح → declined لا عضوية
SUP-02|تحقق إضافي للعملية الحساسة|/mfa/challenge|صاحب جلسة وchallenge|اسم العملية والسياق ومبلغ إن وجد ومدة تحقق|تحقق وتابع~self~POST /auth/mfa/challenge~challenge مرتبط actor/operation → تفويض قصير لا تنفيذ تلقائي لنسخة تغيرت;استخدم رمز استرداد~self~POST /auth/mfa/recovery-challenge~رمز أحادي وعدم تجاوز rate limit;إلغاء العملية~self~POST /auth/mfa/challenge/cancel~يلغي challenge دون اعتماد صرف أو نقل ملكية
SUP-03|التحقق العام من الشهادة|/certificates/:publicId|عام|برنامج وجهة وحالة شهادة واسم عرض بموافقة دون رقم هوية|تحقق من المرجع~public~GET /certificates/:publicId~معدل طلبات محدود → valid/revoked/not_found;عرض البرنامج~public~NAV /programs/:id~مورد منشور فقط;الإبلاغ عن شهادة~self~POST /tickets~مرجع وملاحظة → مراجعة خاصة
SUP-04|تفاصيل تقرير أثر عام|/impact/reports/:id|عام|نسخة مؤرخة وتعريف مؤشرات ومجاميع ورسوم وأثر ومراجع منقحة|تنزيل التقرير~public~GET /public-reports/:id/download~snapshot منشور لا الأصل الخاص;عرض المشروع~public~NAV /projects/:slug~الرابط بحسب نوعه؛ venture إلى /invest وprogram إلى /programs;عرض الجهة~public~NAV /organizations/:slug~ملف عام;نسخ الرابط~public~LOCAL copy canonical URL~رابط النسخة المنشورة بلا token
SUP-05|تتبع ملف التصدير|/app/exports/:jobId|صاحب job أو ممثل جهة مخول|حالة queued/processing/ready/failed/expired وفلاتر ووقت وصلاحية|حدّث الحالة~self~GET /exports/:id~يعاد scope الحالي لا إذن وقت الإنشاء فقط;تنزيل~self~GET /exports/:id/download~ready وgrant ساري → رابط مؤقت;أعد إنشاء تصدير~self~POST /exports/:id/regenerate~failed/expired مع صلاحية التصدير الأصلية → job جديد;حذف نسخة جاهزة~self~POST /exports/:id/revoke~إلغاء وصول الملف لا حذف سجلات المصدر
SUP-06|محفظة المستثمر المؤسسي|/org/:orgId/investments|InvestmentManager/Finance مفوض|Party المؤسسة، التزامات وتسوية وتخصيص وتوزيعات منفصلة عن الفرد|تفاصيل حصة~investment.read~GET /orgs/:orgId/investments/:id~holding للمؤسسة الحالية فقط;تنزيل كشف المؤسسة~investment.export~POST /orgs/:orgId/investment-exports~scope وحقول مؤسسية؛ لا بيانات الفرد;بدء استثمار باسم المؤسسة~commitment.create~NAV /invest/:id/subscribe?context=:orgId~تمثيل مخول وأهلية party المؤسسة
SUP-07|التزام استثماري مؤسسي|/org/:orgId/commitments/:id|ممثل استثمار مخول|جهة دافعة وعرض ونسخة عقد وسعة ومبلغ وموافقات|تأكيد التزام المؤسسة~commitment.manage~POST /orgs/:orgId/commitments/:id/confirm~تفويض توقيع وأهلية ونسخة صالحة;إنشاء دفع~commitment.create~POST /orgs/:orgId/commitments/:id/payment-intents~حدود تمويل واعتمادات المؤسسة مكتملة;إلغاء التزام~commitment.manage~POST /orgs/:orgId/commitments/:id/cancel~policy تسمح وتحرير سعة؛ لا حذف دفع ناجح;تنزيل العقد~investment.read~GET /orgs/:orgId/commitments/:id/agreement~grant ونسخة المؤسسة
SUP-08|مهام فريق الجهة|/org/:orgId/tasks|عضو نشط|مهام مسندة وصلاحية وموعد وحالة ورابط مورد|فتح مهمة~member active~GET /orgs/:orgId/tasks/:id~assignee أو نطاق إذن المورد;استلام مهمة تشغيلية~task.claim~POST /orgs/:orgId/tasks/:id/claim~صلاحية المورد وunassigned → claim ذري;إعادة إسناد~task.assign~POST /orgs/:orgId/tasks/:id/assign~مشرف وفرد مؤهل؛ اعتماد مال يبقى مستقلًا;تعليم إجراء مكتمل~task.complete~POST /orgs/:orgId/tasks/:id/complete~مهام يدوية فقط؛ المالية والأثر تكتمل من domain event لا زر
SUP-09|جلسة تدريب للمتدرب|/app/training/:id/sessions/:sid|متدرب مسجل|عنوان ووقت ومكان ومواد وجلسة عن بعد وحضور للقراءة|انضم للجلسة~self~GET /me/enrollments/:id/sessions/:sid/join-link~مسجل ورابط مزود allowlist وفي نافذة مسموحة;تنزيل مادة~self~GET /documents/:id/download~grant مقرر وفحص نظيف;أضف إلى تقويمي~self~GET /me/enrollments/:id/sessions/:sid/calendar~ICS بالمنطقة الزمنية؛ لا إرسال دعوة لأشخاص آخرين;اعترض على الحضور~self~POST /attendance/:id/objections~سجل هذا المتدرب فقط → review
'@
$groupNames = @{ PUB='01-PUBLIC'; AUTH='02-AUTH'; PER='03-PERSONAL'; ORG='04-ORGANIZATIONS'; BUS='05-BUSINESS'; PRG='06-PROGRAMS'; ADM='07-ADMIN'; SUP='10-SUPPORTING' }
$groupContent = @{}
$index = @('# سجل الصفحات والإجراءات', '', 'يُقرأ مع [عقد الواجهة](../20-UI-CONTRACT.md) و[الصلاحيات](../02-IDENTITY-ROLES-PERMISSIONS.md). جميع الأفعال ترث حالات الخطأ والتأكيد وidempotency حيث تنطبق. الجداول أدناه مواصفات مخططة لا إثبات تنفيذ.', '', '| الصفحة | المسار | الملف |', '|---|---|---|')
$permissionRows = @()
$pageCount = 0
$actionCount = 0
foreach ($line in ($catalog -split "`r?`n")) {
    if ([string]::IsNullOrWhiteSpace($line)) { continue }
    $fields = $line.Split('|')
    if ($fields.Count -ne 6) { throw "Invalid page row: $line" }
    $pageId, $title, $route, $owner, $data, $actionList = $fields
    $group = $pageId.Split('-')[0]
    $fileName = $groupNames[$group] + '.md'
    if (-not $groupContent.ContainsKey($group)) { $groupContent[$group] = @("# $($groupNames[$group]) — مواصفات الصفحات", '', 'كل إجراء أدناه يرث قواعد 20-UI-CONTRACT. حقول النماذج من 21-FORMS-VALIDATION؛ الصلاحيات الجديدة من 08-PERMISSION-EXTENSIONS في هذا المجلد.', '') }
    $groupContent[$group] += @("## $pageId — $title", '', "- **مسار الويب:** ``$route``", "- **السياق والمالك:** $owner", "- **البيانات والمحتوى:** $data", '- **القراءة:** GET للمورد المناظر من 11-API-CONTRACTS؛ scope على الخادم؛ DTO عامة/خاصة حسب السياق. أي عقد قراءة إضافي يثبت في OpenAPI قبل ربط الصفحة.', '- **الحالات المطلوبة:** تحميل، فارغ، فشل قراءة مع إعادة محاولة، ممنوع، غير موجود؛ وفي النماذج حفظ/تحقق/تعارض؛ وفي المال انتظار تأكيد خارجي.', '', '| Action ID | الزر/الإجراء | الصلاحية | العقد | شرط خاص ← النتيجة |', '|---|---|---|---|---|')
    $i = 0
    foreach ($action in $actionList.Split(';')) {
        $af = $action.Split('~')
        if ($af.Count -ne 4) { throw "Invalid action: $action" }
        $i++
        $actionId = '{0}.A{1:00}' -f $pageId, $i
        $groupContent[$group] += "| $actionId | $($af[0]) | $($af[1]) | ``$($af[2])`` | $($af[3]) |"
        $permissionRows += [pscustomobject]@{ Permission=$af[1]; Action=$actionId }
        $actionCount++
    }
    $groupContent[$group] += @('', "**قبول ${pageId}:** تنفيذ الأفعال المعلنة دون زر صامت؛ رفض actor غير مخول ومعرف مورد من جهة أخرى؛ اختبار حالة المورد غير المناسبة لكل mutation؛ تحقق عرض RTL وهاتف. الوصول إلى تبويبات/ملفات داخل الصفحة يعيد فحص الإذن ولا يكتفي بإذن الصفحة الأم.", '')
    $index += "| $pageId — $title | ``$route`` | [$fileName]($fileName) |"
    $pageCount++
}
foreach ($group in $groupNames.Keys) {
    Set-Content -LiteralPath (Join-Path $screenPath ($groupNames[$group] + '.md')) -Value ($groupContent[$group] -join "`n") -Encoding utf8
}
$index += @('', "عدد مواصفات الصفحات/مجموعات المسارات: **$pageCount**. عدد الأفعال الخاصة: **$actionCount**، إضافة إلى 19 إجراء عامًا موروثًا. بعض مجموعات الصفحة تجمع القائمة والتفاصيل أو المسودة والتحرير تحت عقد واحد، ويجب اختبار كل route variant.", '', 'تفاصيل الصلاحيات الموسعة: [08-PERMISSION-EXTENSIONS](08-PERMISSION-EXTENSIONS.md). لا يعني وجود endpoint في هذا السجل أنه منفذ بعد؛ يضاف إلى OpenAPI وخدمة المجال والاختبارات في مرحلته.')
Set-Content -LiteralPath (Join-Path $screenPath 'README.md') -Value ($index -join "`n") -Encoding utf8

$parts = @'
01|تأسيس المستودع والقرارات|لا اعتماديات|00,01,10,16,18|فحص repo وتعليماته؛ تثبيت إصدارات متوافقة وADR؛ workspace web/api/worker؛ PostgreSQL وenv validation؛ health وmigration أولية وCI أساسي|تشغيل موثق على Windows؛ build/types/lint؛ اتصال DB؛ منع production secrets في demo|لا تصميم صفحات المسارات أو ربط دفع إنتاج
02|الهوية والمؤسسات وعزل الصلاحيات|01|02,09,11,12|User وProfile وParty وOrganization وMembership؛ جلسات وتحقق واسترداد؛ دعوات وتبديل سياق؛ policy layer وأدوار؛ AUTH-01..04 وORG-01..05 بالحد الوظيفي|AUTH-01/02/03؛ سحب عضوية يلغي الوصول؛ grants واختبارات cross-tenant في read/write/export|لا منح finance تلقائيًا للـOwner
03|نظام التصميم وقوالب الواجهة|02|03,04,20,21|tokens وخطوط مرخصة؛ RTL/LTR؛ AppShell وforms/tables/dialogs؛ ست شاشات مراجعة ببيانات fixture واضحة؛ PER-01 وPER-18 وglobal controls|keyboard/focus/contrast؛ 360/768/1440؛ كل مكون حالات؛ لا overflow؛ story عربي وإنجليزي|لا اعتبار البيانات المصطنعة backend منفذًا
04|المشاريع والجهات والاستكشاف والخريطة|03|01,04,09,11,12,screens/01-PUBLIC.md|Project polymorphism وpublic projections؛ بحث وفلاتر وصفحات PUB-01..13 بالقراءة للكيانات الموجودة؛ ORG-06/07؛ metadata/locale؛ خرائط list fallback|tenant/public privacy؛ فلاتر URL وback؛ موقع عام فقط؛ حالات فارغ وخطأ|عروض وبرامج غير منفذة لا تقدم CTA ناجحًا وهميًا
05|المشاريع الخيرية والتوثيق والمراجعة|04|05,09,12,21,screens/04-ORGANIZATIONS.md|Campaign وBudget وMilestones وسياسة الهدف؛ ORG-07/08/13؛ مراجعة جهة/مشروع ADM-02/03؛ نشر snapshot؛ نسخ ميزانية وتقارير|انتقالات صحيحة/ممنوعة؛ reviewer منفصل؛ نشر بعد شروط؛ نسخ غير قابلة للمحو|لا قبض مال قبل بناء دفتر المرحلة التالية
06|المساهمات والدفع المحلي والدفتر|05|05,08,09,11,17|Money type وledger؛ PaymentPort ومحاكي؛ inbox/outbox؛ PER-02..05؛ خصوصية contributor؛ ORG-09/10 قراءة؛ callbacks pending|CH-01/02 وFIN-01/02/06 وPRIV-01؛ مثال 100/3؛ webhook duplicate/late؛ لا floating point|المزود محاكى؛ لا مفاتيح إنتاج
07|الصرف والاسترداد والتسوية وإغلاق الخيري|06|05,08,13,15,22|payout reservations وموافقة مستقلة؛ refunds وdisputes؛ reconciliation؛ ORG-11/12؛ ADM-05/06؛ تقرير وإغلاق حلقة خيري كاملة|FIN-03/04/05؛ unknown inquiry؛ نقص رصيد؛ إلغاء بعد صرف؛ LOOP-CH كاملة|لا closed إذا بقي فرق أو دفعة unknown بلا معالجة
08|الشركات والعروض والأهلية وغرفة البيانات|07|06,09,11,12|Venture وOffering وDisclosures وEligibility؛ PUB-07/08؛ PER-07؛ BUS-01..03؛ ADM-04 review؛ أسئلة وNDA/grants|أهلية لا تمنحها capability؛ غرف بيانات معزولة؛ نسخه مستند وقبول؛ حساب أسهم صحيح|لا holding من اهتمام أو commitment
09|الاكتتاب والتخصيص ومحفظة المستثمر|08|06,08,14,15,22|PER-06/08/09؛ BUS-04/05؛ commitments/subscriptions/payments/allocations/holdings؛ محاكي توقيع/إثبات؛ تقارير وتوزيعات وأحداث إغلاق|INV-01..04؛ تزامن سعة؛ فشل minimum/refund؛ إفصاح متغير؛ LOOP-INV بأثر simulated واضح|لا تداول ثانوي ولا ملكية قانونية مدعاة
10|البرامج والطلبات والاختيار والتدريب|09|07,09,11,21|Program وCohort وApplication/Enrollment؛ PUB-09/10؛ PER-10..13؛ PRG-01..05؛ قائمة انتظار وحضور وتقييم واعتراض|PRG-01/02/03؛ تزامن مقعد؛ وقت ومواعيد؛ trainer scope؛ مشاركة ملف بإذن|قبول التدريب ليس قبول وظيفة
11|الوظائف والعروض والتوظيف والمتابعة|10|07,14,15,22|PUB-11؛ PER-14؛ PRG-07..09؛ jobs/referrals/interviews/offers/placements/followups؛ عرض expected مقابل committed|JOB-01/02؛ عدم الرد unknown؛ بدء مؤكد؛ متابعة من تاريخ البدء؛ وصول recruiter محدود|لا عداد توظيف من offer accepted
12|تمويل البرامج والاحتضان والدعم والتطوع|11|07,08,13,17,22|BUS-06؛ PRG-06/10..13؛ PER-15..17؛ منح واتفاقات وبدلات وشهادات وأفكار وmentor؛ حالات مساعدة وتطوع؛ sponsor dashboards|LOOP-EMP وLOOP-INC؛ فصل grant عن equity؛ stipend لا يدفع مرتين؛ شهادات revoke؛ consent وحالات دعم خاصة|سوق مشتريات B2B عام خارج النطاق
13|الإشعارات والإدارة والأثر والدعم الكامل|12|12,13,14,screens/07-ADMIN.md|PER-19/20؛ ADM-01/07/08/09؛ queues وaudit ودعم وتجمد وفك؛ إشعارات/preferences/retries؛ تقارير أثر وتعريفات وexports|OPS-01 وDOC-01؛ unknown outcomes؛ فلاتر تقارير وعملات؛ PII redaction وCSV safety|لا صلاحيات wildcard أو قرارات AI آلية
14|التكامل الشامل والتشغيل والتسليم|13|15,16,17,18,22|تشغيل كل seed stories؛ مراجعة كل action ID؛ اختبار عزل وأموال وأثر؛ visual QA؛ CI/build؛ restore rehearsal؛ runbooks وقرارات بوابات إطلاق|جميع critical tests؛ مصدر كل رقم؛ لا أزرار صامتة؛ أدلة تشغيل ولقطات؛ backup restore؛ gap list للتكاملات الخارجية|الإطلاق المالي الحقيقي مرحلة تفعيل تعتمد معلومات التشغيل ولا يستنتج من اكتمال demo
'@

$roadmap = @('# 19 — خطة التنفيذ على أجزاء', '', 'الترتيب ملزم ما لم يوثق ADR سبب تغيير الاعتماديات. كل جزء جلسة أو عدة جلسات حسب حجم التنفيذ، وليس وعدًا بإنهاء هذا النظام في 14 جلسة قصيرة. لا تتجاوز اختبارات المال والعزل بحجة الانتقال للمرحلة التالية.', '', '| الجزء | الناتج | يعتمد على | برومبت التنفيذ |', '|---|---|---|---|')
foreach ($line in ($parts -split "`r?`n")) {
    if ([string]::IsNullOrWhiteSpace($line)) { continue }
    $f = $line.Split('|')
    if ($f.Count -ne 7) { throw "Invalid part row: $line" }
    $number, $title, $deps, $reads, $scope, $tests, $limits = $f
    $partName = "PART-$number"
    $body = @("# $partName — $title", '', '## البرومبت الجاهز لـCodex', '', "نفّذ هذه المرحلة محليًا داخل مستودع تمكين. اقرأ أولًا ../00-MASTER-PROMPT.md و../PROGRESS.md و../TRACEABILITY.md، ثم المراجع التالية من tamkeen-blueprint: **$reads**. الأرقام تشير إلى أسماء الملفات المرقمة في README. اقرأ كذلك سجلات screens المتعلقة بكل معرف صفحة أدناه.", '', "**الاعتماديات:** $deps. تحقق من الأدلة الفعلية، ولا تفترض أن مرحلة سابقة نفذت لمجرد وجود ملفها.", '', '## النطاق المطلوب', '', $scope, '', '## خطة عمل داخل الجزء', '', '1. افحص الوضع الحالي وحدد فرق المواصفة عن التنفيذ.', '2. ثبّت/حدّث schema وDTO وpermission policy وstate transitions المرتبطة بالنطاق.', '3. نفذ migration وخدمات المعاملات والـAPI قبل ربط واجهات الكتابة.', '4. نفذ الشاشات وأفعالها المسجلة؛ أضف IDs للأفعال اللازمة الجديدة.', '5. اربط البيانات من الخادم، وطبق loading/empty/error/conflict/forbidden والانتظار الخارجي.', '6. اختبر المسار السعيد والفشل والتزامن وعزل الجهات بما يناسب التغيير.', '7. راجع الواجهة بالعربية RTL على الهاتف وسطح المكتب، وعدل المشاكل قبل إغلاق الجزء.', '', '## قبول إلزامي', '', $tests, '', 'أضف typecheck/lint/build المناسبة للملفات المعدلة. الاختبار غير المشغل يسجل غير مشغل مع السبب، ولا يوصف بالناجح. استخدم PostgreSQL حقيقية لاختبار معاملات المال والسعة والعزل.', '', '## حدود المرحلة', '', $limits, '', '## تسليم ونقطة استئناف', '', 'حدّث PROGRESS.md وTRACEABILITY.md بأسماء ملفات الكود وأوامر الاختبار ونتائجها ومعرفات الأفعال المغطاة. اكتب في docs/qa/part-XX ملخص أدلة التشغيل والفشل المتوقع والـscreenshots عند وجود واجهة. إذا احتاج الجزء عدة جلسات، سجل آخر شريحة مكتملة وما بقي دون نقل حالة الجزء إلى مكتمل.', '', '### رسالة بدء قابلة للنسخ', '', "> اقرأ tamkeen-blueprint/parts/$partName.md ونفذه ضمن حدود 00-MASTER-PROMPT. استكمل الموجود، اربط الواجهة بالخادم والسياسات، نفذ معايير القبول، وحدث سجلي التقدم والتتبع. لا تبدأ الجزء التالي قبل تقرير نتيجة هذا الجزء.")
    Set-Content -LiteralPath (Join-Path $partPath "$partName.md") -Value ($body -join "`n") -Encoding utf8
    $roadmap += "| $partName | $title | $deps | [$partName](parts/$partName.md) |"
}
$roadmap += @('', '## ترتيب مراجعات المنتج', '', '- بعد PART-03: مراجعة اللغة البصرية عبر الشاشات الست، ثم إصلاح النظام قبل تكرار واجهاته.', '- بعد PART-07: تجربة متبرع وجمعية ومراجع مالي كاملة من إنشاء مشروع إلى تقرير إغلاق.', '- بعد PART-09: تجربة شركة ومستثمر وتخصيص مثبت محليًا.', '- بعد PART-12: تجربة شاب وراعٍ ومشغل ومدرب وصاحب عمل، بما فيها الانسحاب وعدم التوظيف.', '- بعد PART-14: عرض محلي كامل مع قائمة فجوات الإطلاق الحقيقي، دون ادعاء اعتماد مال أو ملكية من مجرد demo.', '', '## التقدم الآمن', '', 'إذا احتاج تكامل خارجي معلومة غير متاحة، سجل EXTERNAL_BLOCKED لهذا التكامل فقط واستمر باستخدام port محاكى واضح في العمل المستقل. تغيير architecture أو semantics الأموال يحتاج تحديث ADR والمواصفات والاختبارات المرتبطة قبل البناء عليه.')
Set-Content -LiteralPath (Join-Path $basePath '19-IMPLEMENTATION-ROADMAP.md') -Value ($roadmap -join "`n") -Encoding utf8
Write-Output "Generated $pageCount page specifications and $actionCount specific actions, plus 14 implementation parts."
